### PR TITLE
[DO NOT MERGE] Onboarding views + OpenGL

### PR DESCRIPTION
**Pull request by hebasto**
This PR is for testing purpose only to provide designers with CI built binaries for supported platforms.

It combines bitcoin-core/gui-qml#33 and bitcoin-core/gui-qml#124.

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/126)
[macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/126)
[Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/126)

### CODE REVIEW

**Review by shaavan — COMMENTED** [review]
- Tested this PR on a Xiaomi Note 5 Pro, with Android 9 Pie
- I successfully downloaded the app and ran it on my phone.

**Observations:**

Note: These are the things I observed while running the app. They are not intended as a set of suggestions for any specific PR.

1. The Bitcoin core icon is not shown when installing the app but is shown when the app is downloaded.

Frame 2

Of the onboarding views:
Frame 1


1. Text on all the pages overflows.
2. `OptionButton` switches only when they are tapped at the border. Without touching the edge, taping in the center does not change the selected `OptionButton`.
3. The color of the Bitcoin icon is bright green, corresponding to testnet. Don't know if that's a deliberate choice.

**Comment by jarolrod** [comment]
@shaavan thank you for testing on android, that's actually one thing we wanted to quickly confirm about the current master branch in general. But this is about fixing the stuttering issues by moving from 2d rendering to opengl rendering. Please also test on desktop comparing this branch and master to see if there's a considerable difference in how things are rendered in switching through pages + resizing the window

**Comment by shaavan** [comment]
> Seems like this should be feedback on https://github.com/bitcoin-core/gui-qml/pull/124 in consideration of mobile devices.

Yes. And AFAIK, fixing the layout according to the design guide (for example, using _max-width_ instead of _width_) shall fix most of these issues. I shall soon update PR #124 with the layout set.

> Please also test on desktop comparing this branch and master to see if there's a considerable difference in how things are rendered in switching through pages + resizing the window

I shall soon post my observation regarding this.

**Comment by shaavan** [comment]
I could not observe any visible improvement on my desktop using OpenGL.

**Specification:**

Ubuntu 22.04 with Qt version 5.15.3

**Demo:**

|With 2D Rendering (PR#124)|With OpenGL(PR#126)|
|-------------------------|------------------|
|Without OpenGL(1)|With OpenGL|

**Comment by hebasto** [comment]
> I could not observe any visible improvement on my desktop using OpenGL.
> 
> 
> 
> **Specification:**
> 
> 
> 
> Ubuntu 22.04 with Qt version 5.15.3
> 

Do logs confirm OpenGL usage?

**Comment by shaavan** [comment]
I could not find any statement while configuring that talks about using OpenGL.

However, I found a seemingly relevant statement in the debug.log

image

 I used the dynamic build for building this PR. Let me give a try building with static builds as well.

**Review by shaavan — COMMENTED** [review]
I successfully compiled this PR by doing a static build using depends.

**System Specification:**

Ubuntu 22.04 with Qt version 5.15.3

<details open>
<summary> <b>Steps used to compile</b> </summary>
<br>

From `../gui-qml` folder
```
cd depends
make -j8
cd ..
./autogen.sh
CONFIG_SITE=\$PWD/depends/x86_64-pc-linux-gnu/share/config.site ./configure --without-bdb --with-qml
make -j8
```
</details>

I observed considerable improvements with using **OpenGL Rendering** over **2-D Rendering**.

**Demo:**

|With 2D Rendering (PR#124)|With OpenGL(PR#126)|
|-------------------------|------------------|
|Without OpenGL(1)|Screencast from 05-06-22 01 58 18 AM IST|

**Review by jarolrod — COMMENTED** [review]
Concept ACK

I have tested this and compared to master using static builds. There is a huge difference, as expected. I am not including a video demonstration as I'm not sure it would accurately convey the difference. 

OpenGL support is needed for implementing several UI elements as specified in the design files, it's widely superior to 2d rendering for general UI fluidity, and is needed for proper wayland support.

**Comment by jarolrod** [comment]
rebase now that #33 is merged?

**Comment by jarolrod** [comment]
This can be closed now

**Pull request closed without merging**
