### PR TITLE
Introduce Network Traffic  node page

### PR DESCRIPTION
**Pull request by jarolrod**
Based on the following design: [Network Traffic Graph](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App-(Old)?node-id=6262%3A114288&t=IJGP5wcb9JgB0pDK-4)

| dark | light |
| ---- | ----- |
| dark | light |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/286)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/286)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/286)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/286)

### CODE REVIEW

**Comment by jarolrod** [comment]
Updated from [ac2a6ab ](https://github.com/bitcoin-core/gui-qml/commit/ac2a6ab2cc2c9f45a052f24d3060df53dbf72f62)to [66f31a3](https://github.com/bitcoin-core/gui-qml/commit/66f31a300dff175c8ab8ab5a6c6961588655084c), [compare](https://github.com/bitcoin-core/gui-qml/compare/ac2a6ab2cc2c9f45a052f24d3060df53dbf72f62..66f31a300dff175c8ab8ab5a6c6961588655084c)

Changes: Address feedback from @GBKS 
- Fixed gradient getting messed up by moving the painter path back up to the `m_max_y_pos` to keep the linear gradient inside of a box.
- Reduced thickness of lines
- Prevent long time frames from looking erratic by recalculating the moving average values based on a new filter window size. The filter window is now kept to be 10% of the sample size for that time frame.

**Comment by GBKS** [comment]
There's a failing test, should the binaries still be up-to-date with your latest changes?

**Comment by jarolrod** [comment]
Updated from from [66f31a3 ](https://github.com/bitcoin-core/gui-qml/commit/66f31a300dff175c8ab8ab5a6c6961588655084c)to [cda305c](https://github.com/bitcoin-core/gui-qml/commit/cda305c6d8e33cdd17703a9b98e28fbe15c0f00f), [compare](https://github.com/bitcoin-core/gui-qml/compare/66f31a300dff175c8ab8ab5a6c6961588655084c..cda305c6d8e33cdd17703a9b98e28fbe15c0f00f)

Changes: addressed feedback, ready for review

**Comment by jarolrod** [comment]
Updated from [cda305c ](https://github.com/bitcoin-core/gui-qml/commit/cda305c6d8e33cdd17703a9b98e28fbe15c0f00f)to [a90881e](https://github.com/bitcoin-core/gui-qml/commit/a90881ed36e08e74cf7560044d711f647f7be159), [compare](https://github.com/bitcoin-core/gui-qml/compare/cda305c6d8e33cdd17703a9b98e28fbe15c0f00f..a90881ed36e08e74cf7560044d711f647f7be159)

Changes: removed trailing whitespace

**Comment by jarolrod** [comment]
Updated from [a90881e ](https://github.com/bitcoin-core/gui-qml/commit/a90881ed36e08e74cf7560044d711f647f7be159)to [3b046c6 ](https://github.com/bitcoin-core/gui-qml/commit/3b046c68625cdd5abc1a753e85bc08f42d138bbe)
[Compare](https://github.com/bitcoin-core/gui-qml/compare/a90881ed36e08e74cf7560044d711f647f7be159..3b046c68625cdd5abc1a753e85bc08f42d138bbe)

Changes: fix issue with gradient where the gradient only stretches down to the lowest point of the line instead of going to the bottom of the graph itself

| issue | fixed | 
| ----- | ----- |
| issue | Screen Shot 2023-03-12 at 9 44 51 PM |

**Comment by jarolrod** [comment]
Updated from [3b046c6 ](https://github.com/bitcoin-core/gui-qml/commit/3b046c68625cdd5abc1a753e85bc08f42d138bbe)to [ecad4a8](https://github.com/bitcoin-core/gui-qml/commit/ecad4a8fbb39eaf8a0c74a2c506f99847259692e), [compare](https://github.com/bitcoin-core/gui-qml/compare/3b046c68625cdd5abc1a753e85bc08f42d138bbe..ecad4a8fbb39eaf8a0c74a2c506f99847259692e)

Changes: toggle button row fixups

**Comment by jarolrod** [comment]
Updated from [ecad4a8 ](https://github.com/bitcoin-core/gui-qml/commit/ecad4a8fbb39eaf8a0c74a2c506f99847259692e)to [33df602](https://github.com/bitcoin-core/gui-qml/commit/33df602fee354fd2d3d1a3eddd97d57689883139), [compare](https://github.com/bitcoin-core/gui-qml/compare/ecad4a8fbb39eaf8a0c74a2c506f99847259692e..33df602fee354fd2d3d1a3eddd97d57689883139)

Changes: break down into separate components

**Comment by jarolrod** [comment]
Updated from [33df602 ](https://github.com/bitcoin-core/gui-qml/commit/33df602fee354fd2d3d1a3eddd97d57689883139)to [287332b](https://github.com/bitcoin-core/gui-qml/commit/287332be07995c60ebddcb0cf68b078898231304), [compare](https://github.com/bitcoin-core/gui-qml/compare/33df602fee354fd2d3d1a3eddd97d57689883139..287332be07995c60ebddcb0cf68b078898231304)

Changes: fix issue where the colored line was showing next to the border line

**Comment by GBKS** [comment]
I prefer this option over #292, as the information is much easier to understand.

When the graphs are overlaid, as in #292, you mentally have to distinguish the layers. This type of overlay is more appropriate when the there is a correlation between the lines, which we don't have here (as a viewer, you are not looking to understand the relationship between the two lines). So two graphs, underneath each other, is the more appropriate solution, IMHO, for this reason, and for usability.

**Pull request merged**
