### PR TITLE
Add Connection animation to Block Clock connecting state

### PR DESCRIPTION
**Pull request by jarolrod**
| light | dark |
| ----- | ---- |
| animation-light | dark-animation |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/261)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/261)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/261)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/261)

### CODE REVIEW

**Comment by GBKS** [comment]
Thank you for implementing this, I just tested it and have a few thoughts.

Since we have the blinking dots to communicate that a network connection is being established, I don't think we need to show this massive loader right away. Maybe it can only appear after 5 seconds of a blink dot, in case the user gets impatient ("now the app is trying really hard").

Fading the loader in and out somewhat slowly, maybe 600ms, would be nice to avoid this abrupt effect we have right now where it pops in/out instantly.

It looks like the gradient currently goes from yellow to red to the background color. Is it possible to add transparency to this? There's a very slightly funky effect happening right now where the dots on the dial behind the loader get covered up by the last part of the gradient that uses the background color. This could be done later, not sure if anyone really notices this.

Overall, is there any other type of loading the app does that might also need a loader?

On a sidenote, I tested this by disabling wi-fi altogether. Would be awesome if there's a way to detect whether the phone has any type of internet connection and show an appropriate message.

@jarolrod really appreciate how much work you're putting into this app. Hats off to you.

**Comment by hebasto** [comment]
> Based on #252

It has been merged.

**Comment by jarolrod** [comment]
Updated from [e2ecfaf ](https://github.com/bitcoin-core/gui-qml/commit/e2ecfaf1624809a11e5e6d42c331992a5f4b01f3)to [6d97c0a](https://github.com/bitcoin-core/gui-qml/commit/6d97c0a15051caab822a4f55ad79c5bc886bdf6b), [compare](https://github.com/bitcoin-core/gui-qml/compare/e2ecfaf1624809a11e5e6d42c331992a5f4b01f3..6d97c0a15051caab822a4f55ad79c5bc886bdf6b)

Changes: rebased over main

**Comment by jarolrod** [comment]
Updated from [6d97c0a ](https://github.com/bitcoin-core/gui-qml/commit/6d97c0a15051caab822a4f55ad79c5bc886bdf6b)to [3d4a760](https://github.com/bitcoin-core/gui-qml/commit/3d4a76014f1cac0da0c23c1869af531233f7f377), [compare](https://github.com/bitcoin-core/gui-qml/compare/6d97c0a15051caab822a4f55ad79c5bc886bdf6b..3d4a76014f1cac0da0c23c1869af531233f7f377)

Changes: made last color in gradient `transparent` instead of `Theme.color.background`

| master | pr |
| ------ | -- |
| animation-light | Screen Recording 2023-02-21 at 6 55 37 PM |
| dark-animation | pr-dark |

**Comment by jarolrod** [comment]
Closing in favor of https://github.com/bitcoin-core/gui-qml/pull/272

**Pull request closed without merging**
