### PR TITLE
Correct Default Proxy header description on ProxySettings - Follow-up #391

### PR DESCRIPTION
**Pull request by pablomartin4btc**
This is a follow-up from https://github.com/bitcoin-core/gui-qml/pull/391#issuecomment-2030046949.

<details>
<summary>Currently/ <code>main</code> branch screenshot.</summary>

Screenshot from 2024-04-07 23-00-31

</details>
<details>
<summary> This PR branch screenshot.</summary>

image

</details>

### CODE REVIEW

**Comment by pablomartin4btc** [comment]
Gentle reminder to #391's reviewers: @johnny9, @GBKS, @D33r-Gee, @MarnixCroes, @stackingsaunter.

**Review by MarnixCroes — APPROVED** [review]
lgtm

maybe `Tor Proxy` description could be changed also, to
`Run Tor connections through a dedicated proxy.` to be consistent in the wording and the _enable to_ is a bit redundant as well

**Comment by pablomartin4btc** [comment]
Updates:
- Addressed @MarnixCroes's feedback, thanks!

**Review by D33r-Gee — COMMENTED** [review]
tACK d558b05dda37bc135936969d4d53210b51e0e7fc

lgtm, wording is clear...

<details>
<summary>Ubuntu 22.04 Screenshot</summary>

Screenshot 2024-04-08 084731

</details>
<details>
<summary>Android (armv7) Screenshot</summary>

Screenshot_20240408_085820


</details>

**Review by MarnixCroes — APPROVED** [review]
ack d558b05dda37bc135936969d4d53210b51e0e7fc

**Comment by GBKS** [comment]
tACK d558b05

**Pull request merged**
