### PR TITLE
Sync with the main repo

### PR DESCRIPTION
**Pull request by hebasto**
Sync with the main repo up to the latest https://github.com/bitcoin/bitcoin/commit/d76a423809372f30445b6d2249ad3b4a7bd79a43.

No merge conflicts.

Guix build on `x86_64`:
```
4f9abf771fe2ddb777df3f63830ac9a373befc3498449aac1140ed50dde93951  guix-build-6eb6aae5080f/output/aarch64-linux-gnu/SHA256SUMS.part
7d5f51c5dd3ccd1f171e8aeff38c0a23967c021a74b260cace74877037fd7234  guix-build-6eb6aae5080f/output/aarch64-linux-gnu/bitcoin-6eb6aae5080f-aarch64-linux-gnu-debug.tar.gz
d55edaf12c3b81e133ac1bf8b4aaf32c3a9abc385aa360bc9477f733c7772b5c  guix-build-6eb6aae5080f/output/aarch64-linux-gnu/bitcoin-6eb6aae5080f-aarch64-linux-gnu.tar.gz
baa6b7608a75d72d33ab865608b8456b080b678f4a4b6ff22a8574180a0dfc14  guix-build-6eb6aae5080f/output/arm-linux-gnueabihf/SHA256SUMS.part
fec06d9333938f5de954b59e76a072c213caf82e191ca8a354385d241801e1f5  guix-build-6eb6aae5080f/output/arm-linux-gnueabihf/bitcoin-6eb6aae5080f-arm-linux-gnueabihf-debug.tar.gz
ecbe4e619c8319098f45bdfc5bc58d687f38f9895900fb6621a3abab51d1c172  guix-build-6eb6aae5080f/output/arm-linux-gnueabihf/bitcoin-6eb6aae5080f-arm-linux-gnueabihf.tar.gz
65b546de0ecfff3f4da213b733b2996e2c24598e00af5912d002bf812ac320cb  guix-build-6eb6aae5080f/output/arm64-apple-darwin/SHA256SUMS.part
442a88bda61848735a82411f7974544b865c72d0c06f08fbb1a36b161c33c5d7  guix-build-6eb6aae5080f/output/arm64-apple-darwin/bitcoin-6eb6aae5080f-arm64-apple-darwin-unsigned.dmg
c0178ecea52113d196b8c25fd32e91a12e0482f9f73d658c519ba34472bcc471  guix-build-6eb6aae5080f/output/arm64-apple-darwin/bitcoin-6eb6aae5080f-arm64-apple-darwin-unsigned.tar.gz
7400c7567300404022c55fa7f09b535d4408ac6dc2d786716355177135a77347  guix-build-6eb6aae5080f/output/arm64-apple-darwin/bitcoin-6eb6aae5080f-arm64-apple-darwin.tar.gz
c4a9373cc740193e1def3cecd2d22986d01fb6fab512a5eb44ea5df0fa854bcd  guix-build-6eb6aae5080f/output/dist-archive/bitcoin-6eb6aae5080f.tar.gz
36456605c7a90d484ef6886be37d263409f50ea34027eca713bb55479b569dfa  guix-build-6eb6aae5080f/output/powerpc64-linux-gnu/SHA256SUMS.part
05ee9a78f77ed76611304b84f4f6dce360eec1ea34317ed11cae06912e90e1c4  guix-build-6eb6aae5080f/output/powerpc64-linux-gnu/bitcoin-6eb6aae5080f-powerpc64-linux-gnu-debug.tar.gz
0cb7f7f93236c001e3a93a915b2e2b3925b3bf9107375f45528235c470bbb229  guix-build-6eb6aae5080f/output/powerpc64-linux-gnu/bitcoin-6eb6aae5080f-powerpc64-linux-gnu.tar.gz
554043e1c01ef322ef7140532848dc4e565c96eb0215e9c0ba23d0f3fc6622e1  guix-build-6eb6aae5080f/output/powerpc64le-linux-gnu/SHA256SUMS.part
d6ea28e5c27691da92fc6fb7f2d2d61f7722e441f87b2717ef87e06fc664ac8c  guix-build-6eb6aae5080f/output/powerpc64le-linux-gnu/bitcoin-6eb6aae5080f-powerpc64le-linux-gnu-debug.tar.gz
6e7fa9eb187f7fa08516473298fe329de5aa2f0c5bb736e890c41d559945078f  guix-build-6eb6aae5080f/output/powerpc64le-linux-gnu/bitcoin-6eb6aae5080f-powerpc64le-linux-gnu.tar.gz
7b4182211cbabf49af2943018b45063dd022dae56915d33f07c129c37696ccfa  guix-build-6eb6aae5080f/output/riscv64-linux-gnu/SHA256SUMS.part
6ceea478a85b5e66b82f51e5074961e8745204ccb112b71f2582c6e3381d343c  guix-build-6eb6aae5080f/output/riscv64-linux-gnu/bitcoin-6eb6aae5080f-riscv64-linux-gnu-debug.tar.gz
0436946c03ec416022ca34362ecbfe88c12344ad98f01f23362bee08f337d728  guix-build-6eb6aae5080f/output/riscv64-linux-gnu/bitcoin-6eb6aae5080f-riscv64-linux-gnu.tar.gz
c3d64e2f6ea073add3b72187cebe37d8f86af39844e91af09bcadad49d82fba8  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/SHA256SUMS.part
2faaa084edd8fa495ef2dca68015bdb49630ff1c1414d133d972bab9b22e7ae0  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/bitcoin-6eb6aae5080f-x86_64-apple-darwin-unsigned.dmg
de1038050313045d08eb08b257ec2a2f7697cd2c8e9f08fd0b3da6da422f00db  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/bitcoin-6eb6aae5080f-x86_64-apple-darwin-unsigned.tar.gz
50ad7608a74266bc409aaff206a3bccc38313ff62661cfc58fcbb05795a56536  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/bitcoin-6eb6aae5080f-x86_64-apple-darwin.tar.gz
57740566923cac355a3383d1ba3f02999d438de1a4ad599c6cb6f9a2fb2162c9  guix-build-6eb6aae5080f/output/x86_64-linux-gnu/SHA256SUMS.part
ef2e27ffc48e56c4db395ae6af330f1a739bb8e21f00aa57ce79ac5b8d0151f1  guix-build-6eb6aae5080f/output/x86_64-linux-gnu/bitcoin-6eb6aae5080f-x86_64-linux-gnu-debug.tar.gz
a84a87622433d1750d2bd02019dba3148b6ff449fc883f74bed93084963c32bd  guix-build-6eb6aae5080f/output/x86_64-linux-gnu/bitcoin-6eb6aae5080f-x86_64-linux-gnu.tar.gz
e21c3e6f7930a085af8f4cd7755d73214702f96c7625c001b21901f0a522b7da  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/SHA256SUMS.part
02251a57aa71069a7d9b35c8f7e055738f5bd4ef2c3b6e193e75cacebb86cba2  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64-debug.zip
6e61e2c1f2688a02e5314bed594d6dccfaecab671a8ed32fb0dd479d1ea7ed75  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64-setup-unsigned.exe
0f077749c162d35f8f75f86ca7cd2e071261167b1d55074e31352be9f942e6a4  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64-unsigned.tar.gz
234946da0725d782bfc6fd8f0a3f665e8233c27d6eb31ebc51fba0149f1fd3f9  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64.zip
```

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/174)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/174)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/174)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/174)

### CODE REVIEW

**Comment by jarolrod** [comment]
GUIX hashes

x86:
```

```

arm64:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

4f9abf771fe2ddb777df3f63830ac9a373befc3498449aac1140ed50dde93951  guix-build-6eb6aae5080f/output/aarch64-linux-gnu/SHA256SUMS.part
7d5f51c5dd3ccd1f171e8aeff38c0a23967c021a74b260cace74877037fd7234  guix-build-6eb6aae5080f/output/aarch64-linux-gnu/bitcoin-6eb6aae5080f-aarch64-linux-gnu-debug.tar.gz
d55edaf12c3b81e133ac1bf8b4aaf32c3a9abc385aa360bc9477f733c7772b5c  guix-build-6eb6aae5080f/output/aarch64-linux-gnu/bitcoin-6eb6aae5080f-aarch64-linux-gnu.tar.gz
baa6b7608a75d72d33ab865608b8456b080b678f4a4b6ff22a8574180a0dfc14  guix-build-6eb6aae5080f/output/arm-linux-gnueabihf/SHA256SUMS.part
fec06d9333938f5de954b59e76a072c213caf82e191ca8a354385d241801e1f5  guix-build-6eb6aae5080f/output/arm-linux-gnueabihf/bitcoin-6eb6aae5080f-arm-linux-gnueabihf-debug.tar.gz
ecbe4e619c8319098f45bdfc5bc58d687f38f9895900fb6621a3abab51d1c172  guix-build-6eb6aae5080f/output/arm-linux-gnueabihf/bitcoin-6eb6aae5080f-arm-linux-gnueabihf.tar.gz
65b546de0ecfff3f4da213b733b2996e2c24598e00af5912d002bf812ac320cb  guix-build-6eb6aae5080f/output/arm64-apple-darwin/SHA256SUMS.part
442a88bda61848735a82411f7974544b865c72d0c06f08fbb1a36b161c33c5d7  guix-build-6eb6aae5080f/output/arm64-apple-darwin/bitcoin-6eb6aae5080f-arm64-apple-darwin-unsigned.dmg
c0178ecea52113d196b8c25fd32e91a12e0482f9f73d658c519ba34472bcc471  guix-build-6eb6aae5080f/output/arm64-apple-darwin/bitcoin-6eb6aae5080f-arm64-apple-darwin-unsigned.tar.gz
7400c7567300404022c55fa7f09b535d4408ac6dc2d786716355177135a77347  guix-build-6eb6aae5080f/output/arm64-apple-darwin/bitcoin-6eb6aae5080f-arm64-apple-darwin.tar.gz
c4a9373cc740193e1def3cecd2d22986d01fb6fab512a5eb44ea5df0fa854bcd  guix-build-6eb6aae5080f/output/dist-archive/bitcoin-6eb6aae5080f.tar.gz
36456605c7a90d484ef6886be37d263409f50ea34027eca713bb55479b569dfa  guix-build-6eb6aae5080f/output/powerpc64-linux-gnu/SHA256SUMS.part
05ee9a78f77ed76611304b84f4f6dce360eec1ea34317ed11cae06912e90e1c4  guix-build-6eb6aae5080f/output/powerpc64-linux-gnu/bitcoin-6eb6aae5080f-powerpc64-linux-gnu-debug.tar.gz
0cb7f7f93236c001e3a93a915b2e2b3925b3bf9107375f45528235c470bbb229  guix-build-6eb6aae5080f/output/powerpc64-linux-gnu/bitcoin-6eb6aae5080f-powerpc64-linux-gnu.tar.gz
554043e1c01ef322ef7140532848dc4e565c96eb0215e9c0ba23d0f3fc6622e1  guix-build-6eb6aae5080f/output/powerpc64le-linux-gnu/SHA256SUMS.part
d6ea28e5c27691da92fc6fb7f2d2d61f7722e441f87b2717ef87e06fc664ac8c  guix-build-6eb6aae5080f/output/powerpc64le-linux-gnu/bitcoin-6eb6aae5080f-powerpc64le-linux-gnu-debug.tar.gz
6e7fa9eb187f7fa08516473298fe329de5aa2f0c5bb736e890c41d559945078f  guix-build-6eb6aae5080f/output/powerpc64le-linux-gnu/bitcoin-6eb6aae5080f-powerpc64le-linux-gnu.tar.gz
011c891cea6e3e3696b8b78d7d76be46bff2219d671df76965e373e2bb3d2659  guix-build-6eb6aae5080f/output/riscv64-linux-gnu/SHA256SUMS.part
6ceea478a85b5e66b82f51e5074961e8745204ccb112b71f2582c6e3381d343c  guix-build-6eb6aae5080f/output/riscv64-linux-gnu/bitcoin-6eb6aae5080f-riscv64-linux-gnu-debug.tar.gz
0a984800669e64f05a331f38c7afefbbb698df1e9bb8a3b51cac22746cf011e9  guix-build-6eb6aae5080f/output/riscv64-linux-gnu/bitcoin-6eb6aae5080f-riscv64-linux-gnu.tar.gz
c3d64e2f6ea073add3b72187cebe37d8f86af39844e91af09bcadad49d82fba8  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/SHA256SUMS.part
2faaa084edd8fa495ef2dca68015bdb49630ff1c1414d133d972bab9b22e7ae0  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/bitcoin-6eb6aae5080f-x86_64-apple-darwin-unsigned.dmg
de1038050313045d08eb08b257ec2a2f7697cd2c8e9f08fd0b3da6da422f00db  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/bitcoin-6eb6aae5080f-x86_64-apple-darwin-unsigned.tar.gz
50ad7608a74266bc409aaff206a3bccc38313ff62661cfc58fcbb05795a56536  guix-build-6eb6aae5080f/output/x86_64-apple-darwin/bitcoin-6eb6aae5080f-x86_64-apple-darwin.tar.gz
57740566923cac355a3383d1ba3f02999d438de1a4ad599c6cb6f9a2fb2162c9  guix-build-6eb6aae5080f/output/x86_64-linux-gnu/SHA256SUMS.part
ef2e27ffc48e56c4db395ae6af330f1a739bb8e21f00aa57ce79ac5b8d0151f1  guix-build-6eb6aae5080f/output/x86_64-linux-gnu/bitcoin-6eb6aae5080f-x86_64-linux-gnu-debug.tar.gz
a84a87622433d1750d2bd02019dba3148b6ff449fc883f74bed93084963c32bd  guix-build-6eb6aae5080f/output/x86_64-linux-gnu/bitcoin-6eb6aae5080f-x86_64-linux-gnu.tar.gz
e21c3e6f7930a085af8f4cd7755d73214702f96c7625c001b21901f0a522b7da  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/SHA256SUMS.part
02251a57aa71069a7d9b35c8f7e055738f5bd4ef2c3b6e193e75cacebb86cba2  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64-debug.zip
6e61e2c1f2688a02e5314bed594d6dccfaecab671a8ed32fb0dd479d1ea7ed75  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64-setup-unsigned.exe
0f077749c162d35f8f75f86ca7cd2e071261167b1d55074e31352be9f942e6a4  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64-unsigned.tar.gz
234946da0725d782bfc6fd8f0a3f665e8233c27d6eb31ebc51fba0149f1fd3f9  guix-build-6eb6aae5080f/output/x86_64-w64-mingw32/bitcoin-6eb6aae5080f-win64.zip
```

**Comment by jarolrod** [comment]
Performed my own guix build and confirm no conflicts, I performed the sync with the following steps:
```
1. make sure my branch is at the same head as this PR
2. git fetch https://github.com/bitcoin/bitcoin
3. git merge d76a423809372f30445b6d2249ad3b4a7bd79a43
```

Right now, my arm64 hashes and your x86 hashes have a mismatch at the riscv hashes

**Comment by hebasto** [comment]
@jarolrod 
> Right now, my arm64 hashes and your x86 hashes have a mismatch at the riscv hashes

What about your `x86_64` hashes?

QML-specific code could require more efforts to achieve arch-agnostic Guix builds.

**Review by jarolrod — APPROVED** [review]
ACK 6eb6aae5080f

it should be noted we don't have cross-arch reproducibility right now, but this is something that can be addressed at a later stage.

**Comment by hebasto** [comment]
> it should be noted we don't have cross-arch reproducibility right now, but this is something that can be addressed at a later stage.

Maybe open a dedicated issue to track it?

**Pull request merged**
