### PR TITLE
Introduce bitcoin-circle icon

### PR DESCRIPTION
**Pull request by jarolrod**
Introduces the bitcoin-circle from the Bitcoin Icons set. The svg is taken from optimized/filled and the png has been ran through the optimization script.

The current production use-case of this icon will be for the [block clock bitcoin icon](https://www.figma.com/file/GaCoOSNHB2yMB9ThiDtred/Bitcoin-Core-App?node-id=616%3A1918)

The [bitcoin-circle](https://github.com/BitcoinDesign/Bitcoin-Icons/blob/main/optimized/filled/bitcoin-circle.svg) was taken from the [Bitcoin-Icons Repo](https://github.com/BitcoinDesign/Bitcoin-Icons). This was used to generate a PNG of 128x128 size using inkscape. The resulting PNG was then run through the [optimize-pngs.py](https://github.com/bitcoin-core/bitcoin-maintainer-tools/blob/master/optimize-pngs.py) script. The output of the script is as follows: 

```
optimizing bitcoin-circle.png... done
summary:
+++++++++++++++++
bitcoin-circle.png
  size diff from: 2707 to: 1742
  old sha256: 6964aad278ac2408a04826ab91288cc8281f770df191949f368dc2daba9c0477
  new sha256: 6c07903e01c5d936eb57c2808037038a26c98127225351d76bbd2728a919b787

completed. Checksum stable: False. Total reduction: 965 bytes
```

A demo if the icon in action is available at [introduce-bitcoincircle-icon-demo](https://github.com/jarolrod/gui-qml/tree/introduce-blockcircle-icon-demo), below are screenshots from the demo:
 
| dark |
| ---- |
| Screenshot from 2022-09-26 02-25-24 |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/176)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/176)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/176)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/176)

### CODE REVIEW

**Comment by johnny9** [comment]
Can we remove the padding on the icon?

Another consideration is that high dpi devices can result in scaling the image to ~3.5 times the size on desktop so you might want consider generating a larger png. Here is how android handles this. https://developer.android.com/training/multiscreen/screendensities.  The highest dpi they have listed has a scale factor of 4x for "extra-extra-extra-high-density (xxxhdpi)".

**Comment by johnny9** [comment]
https://github.com/johnny9/gui-qml/commit/0d0e51fe1933647b134f38951aecae5ec9b29187 here's a patch to add the QtSvg module. I think a larger PNG will work just fine, though, and then we don't have to worry about any SVG rendering quirks.

**Comment by jarolrod** [comment]
@johnny9 valid concern, we'll discuss on the call tomorrow and check in with the designers on next steps.

**Comment by GBKS** [comment]
Does this apply to all icons in the application?

**Review by johnny9 — APPROVED** [review]
ACK b09bc584bb0172c44376a7af09f877f07110199f

After today's discussion. I think this icon is good to go and we can have an Issue to track adding support for multiple dpi icon support.

**Pull request merged**
