### PR TITLE
Condense onboarding pages

### PR DESCRIPTION
**Pull request by jarolrod**
This condenses the subpages back into the main file for an onboarding view. We can do this now that elements of a view page are in proper components.

The biggest onboarding page, including all subpages, is now only 119 lines.

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/149)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/149)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/149)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/149)

### CODE REVIEW

**Comment by jarolrod** [comment]
updated from [177e47e ](https://github.com/bitcoin-core/gui-qml/commit/177e47e29143e7f2b2628b00149f187492b10b9d)to [1dd2b4d](https://github.com/bitcoin-core/gui-qml/commit/1dd2b4d417e0d0cc2688be5c6078bfca6942b432)

changes: rebased over master

**Comment by jarolrod** [comment]
updated from 1dd2b4d to 454654c

changes: rebased over master and changes on dependent PRs

**Comment by jarolrod** [comment]
updated from 454654c to 846a955

Changes: rebased over changes on master

**Review by shaavan — COMMENTED** [review]
I prefer the implementation on the **main** over this PRs implementation for the following reason.

1. The swipeView in the current implementation allows each subpage to have there own file. And considering the folder structure of src/qml/pages, I think it is better to keep the pages’ implementation separate.
2. The subpages are like branched routes from the main onboarding route. Naming these files like “onboarding1a, onboarding1b” emphasizes this point more strongly than keeping them in the same file.

In the end, this is my first take on this PR, and I would like to listen to your comments on the above points I presented.

**Comment by jarolrod** [comment]
updated from from[ 846a955 ](https://github.com/bitcoin-core/gui-qml/commit/846a9550625b33126bfdb559c159d4149ed57bdc)to[ e2750c3](https://github.com/bitcoin-core/gui-qml/commit/e2750c30166ca12bf5e3323450365916ea071a3a)

changes: rebased over master

**Comment by GBKS** [comment]
An only somewhat related comment, file names are easier to work with when they are descriptive like "onboarding-01-developer-options" rather than just "123" and "abc" style ("onboarding01a", "onboarding01b"). Feel free to ignore as I am not sure what agreed-upon standards are.

**Comment by shaavan** [comment]
I think this PR needs quick back-and-forth discussions from the team. So I suggest taking this PR in the next Bitcoin core App Design call.

**Comment by jarolrod** [comment]
Better to condense and rename into descriptive names, then just condense. Closing for now as not a priority.

**Pull request closed without merging**
