### PR TITLE
build, qt: Amend `fix_riscv_atomic.patch` for riscv64

### PR DESCRIPTION
**Pull request by hebasto**
The amended patch does not introduce cross architecture reproducibility issues (also see https://github.com/bitcoin/bitcoin/pull/25599). Fixes https://github.com/bitcoin-core/gui-qml/pull/174#issuecomment-1252867095.

Guix builds on `x86_64`:
```
7fa526befacec264600bcd19714540f616a2487126f66be4da87d9a7acdd13a1  guix-build-33111dca9e77/output/aarch64-linux-gnu/SHA256SUMS.part
222e6e32db9dcde12a6ee52ee3bdbc54d7373d62972e3e2894b857ca5873c929  guix-build-33111dca9e77/output/aarch64-linux-gnu/bitcoin-33111dca9e77-aarch64-linux-gnu-debug.tar.gz
feee26c4e067f644a9cacc739fd979c1625cbff7d2eaa8b3edc5a8d1c4626349  guix-build-33111dca9e77/output/aarch64-linux-gnu/bitcoin-33111dca9e77-aarch64-linux-gnu.tar.gz
78058bc77f64522041921eb8c8f12739cba5d6490bbc5b8c98c88b8bbbd9a100  guix-build-33111dca9e77/output/arm-linux-gnueabihf/SHA256SUMS.part
2c1e58c1efb51a65641ee9050aed983b360a7891f32fb02a5dea8003b71d2253  guix-build-33111dca9e77/output/arm-linux-gnueabihf/bitcoin-33111dca9e77-arm-linux-gnueabihf-debug.tar.gz
969964dfaaa1ca19884ab738cb1bc74c7b930bdb3e30fdedaf1f9f2a547334ac  guix-build-33111dca9e77/output/arm-linux-gnueabihf/bitcoin-33111dca9e77-arm-linux-gnueabihf.tar.gz
7237e351b399d8a04bbc99e1a8fdabd39459ad4baf37bd96679fb9c4bca71390  guix-build-33111dca9e77/output/arm64-apple-darwin/SHA256SUMS.part
2bacf53c722be4146ff4113de0361f72ba153b9ba9131569eda8c83247ccba81  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin-unsigned.dmg
a77772190890a447859e24e1aad6997a9d539d99694b482f70ef9183815b5f39  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin-unsigned.tar.gz
55101027a3a71ac92069d617704629292efa6005ce26df93df79c30dd2b39702  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin.tar.gz
2bd82ebd304712123ead459f0fa07871d12bb8f83713f048115034e5df42f39b  guix-build-33111dca9e77/output/dist-archive/bitcoin-33111dca9e77.tar.gz
57f3f4878d5e8c7e574c649872f91ea45242f3e3a3d53fdc4d6db4485f152490  guix-build-33111dca9e77/output/powerpc64-linux-gnu/SHA256SUMS.part
194b0fce73d94836e911cc24a5fae65e78d62e33e92e3bb81b6fc27f37eae347  guix-build-33111dca9e77/output/powerpc64-linux-gnu/bitcoin-33111dca9e77-powerpc64-linux-gnu-debug.tar.gz
a9962e0b9c6052bf09ad8aeec1464bd0dad09fac9691f4e9f5eebee5cd2ded4d  guix-build-33111dca9e77/output/powerpc64-linux-gnu/bitcoin-33111dca9e77-powerpc64-linux-gnu.tar.gz
4b56793cf80eb626a3a7196d4b1fb611b6b40bc8652db13eab51acab920cd6af  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/SHA256SUMS.part
67679f4f89eb6d5a5823216b72aaf92f8bad4b1e7c18f42b7503ccd4c7cea2f1  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/bitcoin-33111dca9e77-powerpc64le-linux-gnu-debug.tar.gz
3706c94162f450351b2819c7b2873e49f47b03a2ac94d85a9f077eaeb3196f02  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/bitcoin-33111dca9e77-powerpc64le-linux-gnu.tar.gz
2b51e3f33281fe065b8949ddf15895dc881cfe2a9992919975111c7d62c81968  guix-build-33111dca9e77/output/riscv64-linux-gnu/SHA256SUMS.part
f4c3e0cdb08cbe75b9af5ad6e0a17fcf627ec95b4a70b3af69bb80b0248e1afd  guix-build-33111dca9e77/output/riscv64-linux-gnu/bitcoin-33111dca9e77-riscv64-linux-gnu-debug.tar.gz
3f7169a7bee1ababb558de75766a2077d83acf2501d6f2e4897ceec520637a51  guix-build-33111dca9e77/output/riscv64-linux-gnu/bitcoin-33111dca9e77-riscv64-linux-gnu.tar.gz
44fdf1930e4b13dc61c513c2ae541aa77cdc6dffc8c601d401364a90d7dfe976  guix-build-33111dca9e77/output/x86_64-apple-darwin/SHA256SUMS.part
063aed3472e07356cd4835b6ba5922d41c4069e02ca6ffc7d18e23a12210b733  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin-unsigned.dmg
a49873ab51199b54ce15d93ff42464aa6f46586f9384f54034e7842031c94a43  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin-unsigned.tar.gz
c1565b606198b21f509b637b2ba14366ac63eb946f3390f288cfb1951bcdecac  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin.tar.gz
994ad271ac404c96179afe483f7c299d9391220c9d1017a3bdfb2598ac00d8da  guix-build-33111dca9e77/output/x86_64-linux-gnu/SHA256SUMS.part
1cf9a1049eaae654966fae2010bc4bb13a02130295c4a75a7db092e0d7069594  guix-build-33111dca9e77/output/x86_64-linux-gnu/bitcoin-33111dca9e77-x86_64-linux-gnu-debug.tar.gz
39ace190cd64ac43c18741e9791b3971c3ad9e586a80ba537ffe9792b6252d72  guix-build-33111dca9e77/output/x86_64-linux-gnu/bitcoin-33111dca9e77-x86_64-linux-gnu.tar.gz
70edc42345f9cb965723d099f907082327cabb649c9df15d3750a64433264a26  guix-build-33111dca9e77/output/x86_64-w64-mingw32/SHA256SUMS.part
9b36f66a4fd2c4cd3afdec912bbf7c67c2c79d04498b3e52d27cae3d9c9ce0a1  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-debug.zip
6aa917a5ae2e37a54373a59c3cfb057f0927c06ed6dc5b144709ca56d8ecca75  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-setup-unsigned.exe
36f9a408bcb5256e8fe16a90b57c0498887f33fc4cb822c8de68f01ecc2d2d21  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-unsigned.tar.gz
2b1b5be8722021026ea48ba432acaa43188c737a2bebc3c64b4329bfe13f2f38  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64.zip
```

Guix builds on `arm64`:
```
7fa526befacec264600bcd19714540f616a2487126f66be4da87d9a7acdd13a1  guix-build-33111dca9e77/output/aarch64-linux-gnu/SHA256SUMS.part
222e6e32db9dcde12a6ee52ee3bdbc54d7373d62972e3e2894b857ca5873c929  guix-build-33111dca9e77/output/aarch64-linux-gnu/bitcoin-33111dca9e77-aarch64-linux-gnu-debug.tar.gz
feee26c4e067f644a9cacc739fd979c1625cbff7d2eaa8b3edc5a8d1c4626349  guix-build-33111dca9e77/output/aarch64-linux-gnu/bitcoin-33111dca9e77-aarch64-linux-gnu.tar.gz
78058bc77f64522041921eb8c8f12739cba5d6490bbc5b8c98c88b8bbbd9a100  guix-build-33111dca9e77/output/arm-linux-gnueabihf/SHA256SUMS.part
2c1e58c1efb51a65641ee9050aed983b360a7891f32fb02a5dea8003b71d2253  guix-build-33111dca9e77/output/arm-linux-gnueabihf/bitcoin-33111dca9e77-arm-linux-gnueabihf-debug.tar.gz
969964dfaaa1ca19884ab738cb1bc74c7b930bdb3e30fdedaf1f9f2a547334ac  guix-build-33111dca9e77/output/arm-linux-gnueabihf/bitcoin-33111dca9e77-arm-linux-gnueabihf.tar.gz
7237e351b399d8a04bbc99e1a8fdabd39459ad4baf37bd96679fb9c4bca71390  guix-build-33111dca9e77/output/arm64-apple-darwin/SHA256SUMS.part
2bacf53c722be4146ff4113de0361f72ba153b9ba9131569eda8c83247ccba81  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin-unsigned.dmg
a77772190890a447859e24e1aad6997a9d539d99694b482f70ef9183815b5f39  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin-unsigned.tar.gz
55101027a3a71ac92069d617704629292efa6005ce26df93df79c30dd2b39702  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin.tar.gz
2bd82ebd304712123ead459f0fa07871d12bb8f83713f048115034e5df42f39b  guix-build-33111dca9e77/output/dist-archive/bitcoin-33111dca9e77.tar.gz
57f3f4878d5e8c7e574c649872f91ea45242f3e3a3d53fdc4d6db4485f152490  guix-build-33111dca9e77/output/powerpc64-linux-gnu/SHA256SUMS.part
194b0fce73d94836e911cc24a5fae65e78d62e33e92e3bb81b6fc27f37eae347  guix-build-33111dca9e77/output/powerpc64-linux-gnu/bitcoin-33111dca9e77-powerpc64-linux-gnu-debug.tar.gz
a9962e0b9c6052bf09ad8aeec1464bd0dad09fac9691f4e9f5eebee5cd2ded4d  guix-build-33111dca9e77/output/powerpc64-linux-gnu/bitcoin-33111dca9e77-powerpc64-linux-gnu.tar.gz
4b56793cf80eb626a3a7196d4b1fb611b6b40bc8652db13eab51acab920cd6af  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/SHA256SUMS.part
67679f4f89eb6d5a5823216b72aaf92f8bad4b1e7c18f42b7503ccd4c7cea2f1  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/bitcoin-33111dca9e77-powerpc64le-linux-gnu-debug.tar.gz
3706c94162f450351b2819c7b2873e49f47b03a2ac94d85a9f077eaeb3196f02  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/bitcoin-33111dca9e77-powerpc64le-linux-gnu.tar.gz
2b51e3f33281fe065b8949ddf15895dc881cfe2a9992919975111c7d62c81968  guix-build-33111dca9e77/output/riscv64-linux-gnu/SHA256SUMS.part
f4c3e0cdb08cbe75b9af5ad6e0a17fcf627ec95b4a70b3af69bb80b0248e1afd  guix-build-33111dca9e77/output/riscv64-linux-gnu/bitcoin-33111dca9e77-riscv64-linux-gnu-debug.tar.gz
3f7169a7bee1ababb558de75766a2077d83acf2501d6f2e4897ceec520637a51  guix-build-33111dca9e77/output/riscv64-linux-gnu/bitcoin-33111dca9e77-riscv64-linux-gnu.tar.gz
44fdf1930e4b13dc61c513c2ae541aa77cdc6dffc8c601d401364a90d7dfe976  guix-build-33111dca9e77/output/x86_64-apple-darwin/SHA256SUMS.part
063aed3472e07356cd4835b6ba5922d41c4069e02ca6ffc7d18e23a12210b733  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin-unsigned.dmg
a49873ab51199b54ce15d93ff42464aa6f46586f9384f54034e7842031c94a43  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin-unsigned.tar.gz
c1565b606198b21f509b637b2ba14366ac63eb946f3390f288cfb1951bcdecac  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin.tar.gz
994ad271ac404c96179afe483f7c299d9391220c9d1017a3bdfb2598ac00d8da  guix-build-33111dca9e77/output/x86_64-linux-gnu/SHA256SUMS.part
1cf9a1049eaae654966fae2010bc4bb13a02130295c4a75a7db092e0d7069594  guix-build-33111dca9e77/output/x86_64-linux-gnu/bitcoin-33111dca9e77-x86_64-linux-gnu-debug.tar.gz
39ace190cd64ac43c18741e9791b3971c3ad9e586a80ba537ffe9792b6252d72  guix-build-33111dca9e77/output/x86_64-linux-gnu/bitcoin-33111dca9e77-x86_64-linux-gnu.tar.gz
70edc42345f9cb965723d099f907082327cabb649c9df15d3750a64433264a26  guix-build-33111dca9e77/output/x86_64-w64-mingw32/SHA256SUMS.part
9b36f66a4fd2c4cd3afdec912bbf7c67c2c79d04498b3e52d27cae3d9c9ce0a1  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-debug.zip
6aa917a5ae2e37a54373a59c3cfb057f0927c06ed6dc5b144709ca56d8ecca75  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-setup-unsigned.exe
36f9a408bcb5256e8fe16a90b57c0498887f33fc4cb822c8de68f01ecc2d2d21  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-unsigned.tar.gz
2b1b5be8722021026ea48ba432acaa43188c737a2bebc3c64b4329bfe13f2f38  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64.zip
```

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/175)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/175)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/175)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/175)

### CODE REVIEW

**Comment by jarolrod** [comment]
GUIX hashes

x86:
```

```

arm64:
```
$ find guix-build-$(git rev-parse --short=12 HEAD)/output/ -type f -print0 | env LC_ALL=C sort -z | xargs -r0 sha256sum

7fa526befacec264600bcd19714540f616a2487126f66be4da87d9a7acdd13a1  guix-build-33111dca9e77/output/aarch64-linux-gnu/SHA256SUMS.part
222e6e32db9dcde12a6ee52ee3bdbc54d7373d62972e3e2894b857ca5873c929  guix-build-33111dca9e77/output/aarch64-linux-gnu/bitcoin-33111dca9e77-aarch64-linux-gnu-debug.tar.gz
feee26c4e067f644a9cacc739fd979c1625cbff7d2eaa8b3edc5a8d1c4626349  guix-build-33111dca9e77/output/aarch64-linux-gnu/bitcoin-33111dca9e77-aarch64-linux-gnu.tar.gz
78058bc77f64522041921eb8c8f12739cba5d6490bbc5b8c98c88b8bbbd9a100  guix-build-33111dca9e77/output/arm-linux-gnueabihf/SHA256SUMS.part
2c1e58c1efb51a65641ee9050aed983b360a7891f32fb02a5dea8003b71d2253  guix-build-33111dca9e77/output/arm-linux-gnueabihf/bitcoin-33111dca9e77-arm-linux-gnueabihf-debug.tar.gz
969964dfaaa1ca19884ab738cb1bc74c7b930bdb3e30fdedaf1f9f2a547334ac  guix-build-33111dca9e77/output/arm-linux-gnueabihf/bitcoin-33111dca9e77-arm-linux-gnueabihf.tar.gz
7237e351b399d8a04bbc99e1a8fdabd39459ad4baf37bd96679fb9c4bca71390  guix-build-33111dca9e77/output/arm64-apple-darwin/SHA256SUMS.part
2bacf53c722be4146ff4113de0361f72ba153b9ba9131569eda8c83247ccba81  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin-unsigned.dmg
a77772190890a447859e24e1aad6997a9d539d99694b482f70ef9183815b5f39  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin-unsigned.tar.gz
55101027a3a71ac92069d617704629292efa6005ce26df93df79c30dd2b39702  guix-build-33111dca9e77/output/arm64-apple-darwin/bitcoin-33111dca9e77-arm64-apple-darwin.tar.gz
2bd82ebd304712123ead459f0fa07871d12bb8f83713f048115034e5df42f39b  guix-build-33111dca9e77/output/dist-archive/bitcoin-33111dca9e77.tar.gz
57f3f4878d5e8c7e574c649872f91ea45242f3e3a3d53fdc4d6db4485f152490  guix-build-33111dca9e77/output/powerpc64-linux-gnu/SHA256SUMS.part
194b0fce73d94836e911cc24a5fae65e78d62e33e92e3bb81b6fc27f37eae347  guix-build-33111dca9e77/output/powerpc64-linux-gnu/bitcoin-33111dca9e77-powerpc64-linux-gnu-debug.tar.gz
a9962e0b9c6052bf09ad8aeec1464bd0dad09fac9691f4e9f5eebee5cd2ded4d  guix-build-33111dca9e77/output/powerpc64-linux-gnu/bitcoin-33111dca9e77-powerpc64-linux-gnu.tar.gz
4b56793cf80eb626a3a7196d4b1fb611b6b40bc8652db13eab51acab920cd6af  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/SHA256SUMS.part
67679f4f89eb6d5a5823216b72aaf92f8bad4b1e7c18f42b7503ccd4c7cea2f1  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/bitcoin-33111dca9e77-powerpc64le-linux-gnu-debug.tar.gz
3706c94162f450351b2819c7b2873e49f47b03a2ac94d85a9f077eaeb3196f02  guix-build-33111dca9e77/output/powerpc64le-linux-gnu/bitcoin-33111dca9e77-powerpc64le-linux-gnu.tar.gz
2b51e3f33281fe065b8949ddf15895dc881cfe2a9992919975111c7d62c81968  guix-build-33111dca9e77/output/riscv64-linux-gnu/SHA256SUMS.part
f4c3e0cdb08cbe75b9af5ad6e0a17fcf627ec95b4a70b3af69bb80b0248e1afd  guix-build-33111dca9e77/output/riscv64-linux-gnu/bitcoin-33111dca9e77-riscv64-linux-gnu-debug.tar.gz
3f7169a7bee1ababb558de75766a2077d83acf2501d6f2e4897ceec520637a51  guix-build-33111dca9e77/output/riscv64-linux-gnu/bitcoin-33111dca9e77-riscv64-linux-gnu.tar.gz
44fdf1930e4b13dc61c513c2ae541aa77cdc6dffc8c601d401364a90d7dfe976  guix-build-33111dca9e77/output/x86_64-apple-darwin/SHA256SUMS.part
063aed3472e07356cd4835b6ba5922d41c4069e02ca6ffc7d18e23a12210b733  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin-unsigned.dmg
a49873ab51199b54ce15d93ff42464aa6f46586f9384f54034e7842031c94a43  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin-unsigned.tar.gz
c1565b606198b21f509b637b2ba14366ac63eb946f3390f288cfb1951bcdecac  guix-build-33111dca9e77/output/x86_64-apple-darwin/bitcoin-33111dca9e77-x86_64-apple-darwin.tar.gz
994ad271ac404c96179afe483f7c299d9391220c9d1017a3bdfb2598ac00d8da  guix-build-33111dca9e77/output/x86_64-linux-gnu/SHA256SUMS.part
1cf9a1049eaae654966fae2010bc4bb13a02130295c4a75a7db092e0d7069594  guix-build-33111dca9e77/output/x86_64-linux-gnu/bitcoin-33111dca9e77-x86_64-linux-gnu-debug.tar.gz
39ace190cd64ac43c18741e9791b3971c3ad9e586a80ba537ffe9792b6252d72  guix-build-33111dca9e77/output/x86_64-linux-gnu/bitcoin-33111dca9e77-x86_64-linux-gnu.tar.gz
70edc42345f9cb965723d099f907082327cabb649c9df15d3750a64433264a26  guix-build-33111dca9e77/output/x86_64-w64-mingw32/SHA256SUMS.part
9b36f66a4fd2c4cd3afdec912bbf7c67c2c79d04498b3e52d27cae3d9c9ce0a1  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-debug.zip
6aa917a5ae2e37a54373a59c3cfb057f0927c06ed6dc5b144709ca56d8ecca75  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-setup-unsigned.exe
36f9a408bcb5256e8fe16a90b57c0498887f33fc4cb822c8de68f01ecc2d2d21  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64-unsigned.tar.gz
2b1b5be8722021026ea48ba432acaa43188c737a2bebc3c64b4329bfe13f2f38  guix-build-33111dca9e77/output/x86_64-w64-mingw32/bitcoin-33111dca9e77-win64.zip
```

**Comment by jarolrod** [comment]
confirming cross-arch reproducibility

**Comment by hebasto** [comment]
Added my `arm64` Guix build hashes to the PR description.

**Review by jarolrod — APPROVED** [review]
ACK 33111dca9e7705943097cfb767acdccad5d65083

Confirms this fixes the cross-arch reproducibility issue. This differs from the linked patch because it is removing https://github.com/bitcoin-core/gui-qml/pull/30 in this PR, rather than reverting and applying the patch. This is fine to do.

**Pull request merged**
