### PR TITLE
ci, build: Update GHA actions and fix build bugs

### PR DESCRIPTION
**Pull request by hebasto**
The second commit has been cherry-picked from https://github.com/bitcoin/bitcoin/pull/29195.

Link to github actions build artifacts:

[Build Artifacts](https://github.com/bitcoin-core/gui-qml/actions/runs/9242930899)

### CODE REVIEW

**Review by pablomartin4btc — APPROVED** [review]
ACK a4855332d4956ebc795734ae790eb7d3fe971b7a

**Review by johnny9 — APPROVED** [review]
ACK a4855332d4956ebc795734ae790eb7d3fe971b7a

**Review by MarnixCroes — APPROVED** [review]
ack a4855332d4956ebc795734ae790eb7d3fe971b7a

**Comment by hebasto** [comment]
@MarnixCroes 
> ack [a485533](https://github.com/bitcoin-core/gui-qml/commit/a4855332d4956ebc795734ae790eb7d3fe971b7a)

Thank you for your review and approval!

FYI, the lowercase "ack" is not recognized by the `github-merge.py` script.

**Pull request merged**
