### PR TITLE
Disable prune target setting when prune is disabled, introduce Disabled Setting color animation state

### PR DESCRIPTION
**Pull request by jarolrod**
This disables the prune target ValueInput setting when the prune enabled/disabled Switch Setting is disabled. Also introduces the "DISABLED" state in accordance with the design file.

light

| enabled | disabled |
| ------- | -------- |
| Screen Shot 2023-02-01 at 4 44 37 AM | Screen Shot 2023-02-01 at 4 44 42 AM |

dark
| enabled | disabled |
| ------- | -------- |
| Screen Shot 2023-02-01 at 4 44 03 AM | Screen Shot 2023-02-01 at 4 44 14 AM |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/<PR>)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/<PR>)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/<PR>)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/<PR>)

### CODE REVIEW

**Comment by jarolrod** [comment]
updated from[ d42b30d ](https://github.com/bitcoin-core/gui-qml/commit/d42b30db75a8d1bfaab11658be50af2df41c0662)to [a896c21](https://github.com/bitcoin-core/gui-qml/commit/a896c2141b9e218261c786696b47ec39a7821f2f), [compare](https://github.com/bitcoin-core/gui-qml/compare/d42b30db75a8d1bfaab11658be50af2df41c0662..a896c2141b9e218261c786696b47ec39a7821f2f)

changes: rebased over main

**Comment by jarolrod** [comment]
Updated from [7c3f94d ](https://github.com/bitcoin-core/gui-qml/commit/7c3f94d8e95ffd815f0d6aa0bd82b079871e4489)to [a896c21](https://github.com/bitcoin-core/gui-qml/commit/a896c2141b9e218261c786696b47ec39a7821f2f), [compare](https://github.com/bitcoin-core/gui-qml/compare/7c3f94d8e95ffd815f0d6aa0bd82b079871e4489..a896c2141b9e218261c786696b47ec39a7821f2f)

changes: reversed an accidental push

**Comment by hebasto** [comment]
> based on #241

It has been just merged. Rebase?

**Comment by jarolrod** [comment]
Updated from [a896c21 ](https://github.com/bitcoin-core/gui-qml/commit/a896c2141b9e218261c786696b47ec39a7821f2f)to [cfe446f ](https://github.com/bitcoin-core/gui-qml/commit/cfe446f812a0d57683151f4bd156ec095882eaf6), [Compare](https://github.com/bitcoin-core/gui-qml/compare/a896c2141b9e218261c786696b47ec39a7821f2f..cfe446f812a0d57683151f4bd156ec095882eaf6)

changes: rebased over main

**Comment by jarolrod** [comment]
Updated from [cfe446f ](https://github.com/bitcoin-core/gui-qml/commit/cfe446f812a0d57683151f4bd156ec095882eaf6)to [ac37e32](https://github.com/bitcoin-core/gui-qml/commit/ac37e3212ba41e6fb5e0504f447addee9a96eadb), [compare](https://github.com/bitcoin-core/gui-qml/compare/cfe446f812a0d57683151f4bd156ec095882eaf6..ac37e3212ba41e6fb5e0504f447addee9a96eadb)

changes: fixed indentation

**Review by johnny9 — APPROVED** [review]
ACK ac37e3212ba41e6fb5e0504f447addee9a96eadb

**Pull request merged**
