### PR TITLE
Support detail item inside option button

### PR DESCRIPTION
**Pull request by promag**
Allow a custom inlined item on the right-hand side of the `OptionButton`:

https://user-images.githubusercontent.com/3534524/148144944-165f657a-e918-47ab-92f7-5641faf095f8.mov

Links for Windows, macOS, and Android build artifacts.

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/103)
[macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/103)
[Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/103)

### CODE REVIEW

**Comment by promag** [comment]
Best reviewed without whitespace changes.

**Comment by hebasto** [comment]
> Allow a custom inlined item on the right-hand side of the `OptionButton`:

Could there be an issue with RTL writing systems?

**Comment by promag** [comment]
> RTL writing systems

I don't think so. Maybe we should raise that concern in the next meeting with designers.

**Review by jarolrod — APPROVED** [review]
tACK 898d6726308d0aa665aadf534ab067a383b7bac8

nice! cleaner implementation than the relevant changes in 5483b128e9f33557a292f5cc6742054eca406e84

**Comment by GBKS** [comment]
@hebasto I am not sure what (if anything) is required for RTL writing systems for this type of component. I'll put it on my list and do a bit of research.

**Review by hebasto — APPROVED** [review]
ACK a55553c560b80e8cc8409937e3ba9c97d4ee5f85

**Pull request merged**
