### PR TITLE
Contain oboarding information in a ScrollView (Option 1)

### PR DESCRIPTION
**Pull request by johnny9**
Addresses https://github.com/bitcoin-core/gui-qml/issues/186

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/191)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/191)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/191)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/191)

### CODE REVIEW

**Review by jarolrod — COMMENTED** [review]
I see an issue with determining the height of the child content as shown in the below screenshot (the bottom text of that page is cut off by the button):

Screenshot_20221207-013240

**Comment by hebasto** [comment]
Rebase?

**Comment by johnny9** [comment]
Update from[ 9697acf ](https://github.com/bitcoin-core/gui-qml/commit/9697acf0a8ec542ab5a253878506665fcaf89986)to 4bd5103
  - rebased with main

**Comment by jarolrod** [comment]
needs rebase again

**Comment by johnny9** [comment]
Update from[ 4bd5103 ](https://github.com/bitcoin-core/gui-qml/commit/4bd5103f24d9f5417c3cbfa02a15e299358700cc)to 8feb1a0:
  - rebased with main

**Review by jarolrod — COMMENTED** [review]
This doesn't work well when using a tiling window manager because the continue button isn't reachable when the window size becomes small:
191-pr

**Comment by jarolrod** [comment]
In split-screen view on android, the continue button also is not accessible. This works in pop-up view though:

Screenshot_20221220-175155

**Pull request closed without merging**
