### PR TITLE
Introduce Wallet main pages

### PR DESCRIPTION
**Pull request by johnny9**
Adds DesktopWallets.qml and MobileWallets.qml. These pages are the central navigation points for the application when wallets are enabled.

A core piece of the page is controlling the navigation flow between the sub pages of the wallet application. For the desktop implementation, a new NavigationBar design is used along with a Stack layout to hold the pages. For mobile, a DirectionalStackView is used to push and pop the wallet sub pages based on the UX designed flow.

[Build Artifacts]()

### CODE REVIEW

**Review by pablomartin4btc — COMMENTED** [review]
tACK fd5704daecb2d74247f95194204e2bae991c0c87

So far so good, I like it.

A few observations:
<details>
<summary>1. First screen after onboarding or once onboarded when app starts (wallet loaded/ no wallet).</summary>

Screenshot from 2024-03-13 13-36-46

I see there's no difference if we have a wallet loaded or not (I haven't checked the code yet), I guess this is why the PR is still on draft, in Figma I found this model (please check top left small wallet icon):

image

Should we don't have a splash-screen or initial window as we have in QT project?

image

Checking in Figma, I couldn't find any reference for such thing, perhaps I missed or was already discused that was not necessary.

</details>

<details>
<summary>2. BlockClock small icon at the top taskbar (?) and BlockClock details view as in Figma.</summary>

Screenshot from 2024-03-13 13-37-02

The BlockCount looks like fixed at the top and should be centered as it's shown on Figma:

Screenshot from 2024-03-14 11-00-31

Also, the top BlockCount small icon looks a bit empty as is, I see in Figma there's a (÷) symbol inside it (?):

Screenshot from 2024-03-14 11-35-13

That's when the app is still trying to sync, not sure when it's completed (100% as the 1st screenshot I put on this bullet point), how the BlockCount small icon would look like, I couldn't find one in Figma among the options:   

Screenshot from 2024-03-14 11-37-12

</details>

Figma design [source](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?type=design&mode=design) for reference.

Code-wise, is it possible to split it in different and more modular commits?

nit: "qml:" prefix in the PRs title isn't necessary.

cc @GBKS for his opinion on the obs.

**Comment by GBKS** [comment]
Just tested because of the mention and looks like a great start. Lots of details to tweak, of course, as pablo pointed out, but it's also a draft PR. Is there anything specific to give feedback on at the moment?

**Review by D33r-Gee — COMMENTED** [review]
tACK fd5704d on Ubuntu 22.04 and Android (armv7)

Great progress! Looks like the base is there for wallet functionality

<details>
<summary>On Ubuntu:</summary>

img(Screenshot 2024-03-20 103916)

</details>

<details>
<summary>Gotta say the Android version looks great:</summary>

android_wallet_1 android_wallet_2

*white bar appeared after capturing the screen...

</details>

**Comment by johnny9** [comment]
Update from 4b43dfa to 25bbfeb 
 - Rebased with main
 - Removed mobile desktop pages
 - Created commits for each new Icon
 - Created commits for each separate functional piece.

**Comment by johnny9** [comment]
from 25bbfeb to  b5a1356:
  - Removed mini blockclock implementation. Will add it later as a separate PR.

**Review by MarnixCroes — COMMENTED** [review]
did some manual testing on desktop, looks good 

- there is a bug where sometimes the gear-outline icon is highlighted, while not selected. this can happen after having minimized the window. (happened twice, not sure exactly how to repro)

- nit: the animation when moving hover away from settings (small flash) &  removing selection from settings is different than the others

[Screencast from 02-04-2024 10:57:34.webm](https://github.com/bitcoin-core/gui-qml/assets/93143998/a4a49328-da97-465c-a7de-9fabc9d7224b)

**Comment by johnny9** [comment]
Update from b5a1356 to[ 37e3af6](https://github.com/bitcoin-core/gui-qml/commit/37e3af6cd67cc9495f13c22936315e893ce8c8dc)
 - Fix for gear icon transitioning to blank as pointed out by @MarnixCroes 
 - Set anchors.centerIn=parent for the BlockClock

**Comment by johnny9** [comment]
>     * there is a bug where sometimes the gear-outline icon is highlighted, while not selected. this can happen after having minimized the window. (happened twice, not sure exactly how to repro)

I haven't had this happen yet but i wonder if it was fixed when i fixed the color change animation for it

**Review by MarnixCroes — APPROVED** [review]
tested on desktop, lgtm 37e3af6cd67cc9495f13c22936315e893ce8c8dc

**Review by D33r-Gee — COMMENTED** [review]
tACK 37e3af6cd67cc9495f13c22936315e893ce8c8dc

Works as expected



<details>
<summary>Ubuntu 22.04 screenshot</summary>

Screenshot 2024-04-05 123438

</details>

**Review by pablomartin4btc — APPROVED** [review]
re tACK 37e3af6cd67cc9495f13c22936315e893ce8c8dc

Changes since my last review:
<ul> :white_check_mark:  Code change was split in separate commits (checked them all), which looks much better organised now.</ul>
<ul> :white_check_mark: `BlockClock` looks centered now.</ul>
<ul> :white_check_mark:  I couldn't reproduce the <a href="https://github.com/bitcoin-core/gui-qml/pull/389#pullrequestreview-1973110374">issue reported</a> by @MarnixCroes with the video, perhaps was fixed with the gear icon transitioning to blank (?).</ul>
<ul> :white_check_mark:  looking forward to see this feature: "<i>Removed mini blockclock implementation. Will add it later as a separate PR.</i>"</ul>
<ul> :o: commit 6e42abc89304ee0ebe22a16d561cd8813b687548 (<code>qml: Add property to hide NetworkIndicator on BlockClock page</code>), what this should do? I think I'm missing something because on Desktop mode, I made it visible (<code>showNetworkIndicator: true</code>) on <code>mainnet</code> but I don't see the difference. Could you please shed some light on this?</ul>

**Comment by johnny9** [comment]
>     ⭕ commit [6e42abc](https://github.com/bitcoin-core/gui-qml/commit/6e42abc89304ee0ebe22a16d561cd8813b687548) (`qml: Add property to hide NetworkIndicator on BlockClock page`), what this should do? I think I'm missing something because on Desktop mode, I made it visible (`showNetworkIndicator: true`) on `mainnet` but I don't see the difference. Could you please shed some light on this?

This will show the network indicator if its not on mainnet (testnet/signet) on the block clock control. The reason i added the bool is because it is redundant in desktop wallet mode because the indicator is already at the top in the navigation bar.

**Pull request merged**
