### PR TITLE
rework Onboardinginfo into informationpage

### PR DESCRIPTION
**Pull request by jarolrod**
based on https://github.com/bitcoin-core/gui-qml/pull/192

This encapsulates the page logic for the onboarding pages into OnboardingInfo, which is then renamed to InformationPage; because now this can be used for reusable `Settings` pages and not just the onboarding views.

This has the benefit of removing a ton of duplicated code around page declaration, but also sets us up to introduce the ScrollView and have it be effective for all pages that use InformationPage, which in turn are all of the views aside from the node view.

Bundled in this change is an update to ensure that we are using the qml translator function for all strings that are a part of the onboarding views.

### Master

| master-1 | master-2 | master-3 | master-4 | master-5 |
| -------- | -------- | -------- | -------- | -------- |
| master-1 | master-2 | master-3 | master-4 | master-5 |

| master-6 | master-7 | master-8 | master-9 | master-10 |
| -------- | -------- | -------- | -------- | --------- |
| master-6 | master-7 | master-8 | master-9 | master-10 |

### PR

| pr-1 | pr-2 | pr-3 | pr-4 | pr-5 |
| ---- | ---- | ---- | ---- | ---- |
| pr-1 | pr-2 | pr-3 | pr-4 | pr-5 |

| pr-6 | pr-7 | pr-8 | pr-9 | pr-10 |
| ---- | ---- | ---- | ---- | ----- |
| pr-6 | pr-7 | pr-8 | pr-9 | pr-10 |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/193)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/193)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/193)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/193)

### CODE REVIEW

**Comment by jarolrod** [comment]
Converting to draft until i fix the width issue on android

**Comment by jarolrod** [comment]
Updated from 7beeb7e to 90f46d3 ([pr193.01](https://github.com/jarolrod/gui-qml/tree/pr193.01) -> [pr193.02](https://github.com/jarolrod/gui-qml/tree/pr193.02), [diff](https://github.com/jarolrod/gui-qml/compare/pr193.01..pr193.02)) 

changes: 
- rebased over changes to https://github.com/bitcoin-core/gui-qml/pull/192
- include one more commit that is a stylistic cleanup for the logic around updating the swipeview's index

**Comment by hebasto** [comment]
Suggesting to rebase to fix CI tasks.

**Comment by jarolrod** [comment]
updated from 90f46d3 to 183be5c ([pr193.02](https://github.com/jarolrod/gui-qml/tree/pr193.02) -> [pr193.03](https://github.com/jarolrod/gui-qml/tree/pr193.03), [diff](https://github.com/jarolrod/gui-qml/compare/pr193.02..pr193.03))

changes: rebased over master

**Comment by hebasto** [comment]
> based on #192

#192 has been just merged. Rebase?

**Review by johnny9 — APPROVED** [review]
ACK 183be5c9698166ca6d01a91f56b3c09fb0595f64

I think this is a significant improvement. The parameter list for the InformationPage is a little crazy but the onboarding page definitions are much easier to manage.

The views render as expected and no qml warnings.

**Pull request merged**
