### PR TITLE
ValueInput "EMPTY" state

### PR DESCRIPTION
**Pull request by jarolrod**
This adds an `"EMPTY"` state to `ValueInput`, as specified in the [design file](https://www.figma.com/file/ek8w3n3upbluw5UL2lGhRx/Bitcoin-Core-App-Design?node-id=6079%3A166395&t=zvbm4HW9rxQf4iBb-4).

This state is only added to `ValueInput` because the `Setting` control should not care about this. All other states continue to function as normal*.

### Light

| EMPTY | FILLED | HOVER | ACTIVE |
| ----- | ------ | ----- | ------ |
| Screen Shot 2023-02-10 at 5 26 04 PM | Screen Shot 2023-02-10 at 5 24 42 PM | Screen Shot 2023-02-10 at 5 24 57 PM | Screen Shot 2023-02-10 at 5 25 18 PM |

### Dark

| EMPTY | FILLED | HOVER | ACTIVE |
| ----- | ------ | ----- | ------ |
| Screen Shot 2023-02-10 at 5 23 43 PM | Screen Shot 2023-02-10 at 5 24 00 PM | Screen Shot 2023-02-10 at 5 24 11 PM | Screen Shot 2023-02-10 at 5 24 28 PM |

*the Setting control loses the active state when the mouse moves away from it, will be addressed in a follow-up.

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/256)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/256)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/256)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/256)

### CODE REVIEW

**Comment by jarolrod** [comment]
Updated from [e7a6997 ](https://github.com/bitcoin-core/gui-qml/commit/e7a6997bef2314f6389d16e2f78b2899418551d2)to [26aa64c](https://github.com/bitcoin-core/gui-qml/commit/26aa64c94c6ad215112e7242ec0d91126a69f433), [compare](https://github.com/bitcoin-core/gui-qml/compare/e7a6997bef2314f6389d16e2f78b2899418551d2..26aa64c94c6ad215112e7242ec0d91126a69f433)

changes: rebased over main and resolved conflicts

**Comment by hebasto** [comment]
> Based on #255

It has just been merged. Rebase?

**Comment by jarolrod** [comment]
Updated from [26aa64c ](https://github.com/bitcoin-core/gui-qml/commit/26aa64c94c6ad215112e7242ec0d91126a69f433)to [85d4cf0](https://github.com/bitcoin-core/gui-qml/commit/85d4cf0420f8c903a1e60ce05f6de0a361dd53aa), [compare](https://github.com/bitcoin-core/gui-qml/compare/26aa64c94c6ad215112e7242ec0d91126a69f433..85d4cf0420f8c903a1e60ce05f6de0a361dd53aa)

changes: rebased over main

**Comment by jarolrod** [comment]
Updated from[ 85d4cf0 ](https://github.com/bitcoin-core/gui-qml/commit/85d4cf0420f8c903a1e60ce05f6de0a361dd53aa)to [1a7c3ce](https://github.com/bitcoin-core/gui-qml/commit/1a7c3cec05f01b377904b5f58e71c092f5a74cb8), [compare](https://github.com/bitcoin-core/gui-qml/compare/85d4cf0420f8c903a1e60ce05f6de0a361dd53aa..1a7c3cec05f01b377904b5f58e71c092f5a74cb8)

Changes:
- now based on https://github.com/bitcoin-core/gui-qml/pull/271 to not conflict
- Removed an explicit `"EMPTY"` state in favor of a check on `filled` and feeding back either the `"EMPTY"` or `"FILLED"` colors and in the case of `"HOVER"`, the `"EMPTY"` or `"HOVER"` colors.

**Comment by hebasto** [comment]
> based on https://github.com/bitcoin-core/gui-qml/pull/271

https://github.com/bitcoin-core/gui-qml/pull/271 has just been merged.

**Comment by jarolrod** [comment]
Updated from [1a7c3ce ](https://github.com/bitcoin-core/gui-qml/commit/1a7c3cec05f01b377904b5f58e71c092f5a74cb8)to [003f174](https://github.com/bitcoin-core/gui-qml/commit/003f1740e0ab5b6de6d872e107275df248f1ab1c), [compare](https://github.com/bitcoin-core/gui-qml/compare/1a7c3cec05f01b377904b5f58e71c092f5a74cb8..003f1740e0ab5b6de6d872e107275df248f1ab1c)

Changes: rebased over main

**Comment by GBKS** [comment]
ACK 003f1740e0ab5b6de6d872e107275df248f1ab1c

**Pull request merged**
