### PR TITLE
Sync with the main repo

### PR DESCRIPTION
**Pull request by hebasto**
Sync with the main repo up to https://github.com/bitcoin-core/gui/commit/446b706696451ae1a66ac416f347d734c5741d7c

To verify:
```
$ cd ../gui && git log --oneline > /tmp/gui && cd ../gui-qml && git log --oneline > /tmp/gui-qml && diff -u /tmp/gui /tmp/gui-qml
```

### CODE REVIEW

**Comment by hebasto** [comment]
cc @promag @jarolrod

**Review by promag — COMMENTED** [review]
Code review ACK ac29328fcd736407bfbe80d73c108a0cd335a652, parent commits are correct.

**Comment by hebasto** [comment]
A script to verify this PR has been added to the OP.

**Review by jarolrod — COMMENTED** [review]
post-merge ACK, verified correctness of sync

**Pull request merged**
