### PR TITLE
Sync with the main repo

### PR DESCRIPTION
**Pull request by hebasto**
Sync with the main repo up to the latest https://github.com/bitcoin/bitcoin/commit/ab42b2ebdbf61225e636e4c00068fd29b2790d41, which includes the recent changes in the CI.

There is no downloadable artifacts support for now. It will be done in a separated PR(s).

Additionally:
- The code was adjusted to reflect changes from [PR27419](https://github.com/bitcoin/bitcoin/pull/27419), [PR27491](https://github.com/bitcoin/bitcoin/pull/27491), [PR27576](https://github.com/bitcoin/bitcoin/pull/27576) and [PR27636](https://github.com/bitcoin/bitcoin/pull/27636).
- Fixed `modernize-use-default-member-init` clang-tidy warnings.
- The ARM task has been temporarily disabled until the issue with the depends cache is resolved.

Guix builds:
```
e92b8c4c3298165edb1a0e85ee516d52c81af1269405dcbc6520e63069de2363  guix-build-b3261144c892/output/aarch64-linux-gnu/SHA256SUMS.part
939c6c002490d5649bdbfabacd20cd2270b41b20b7b3a254c9fcd5780209900d  guix-build-b3261144c892/output/aarch64-linux-gnu/bitcoin-b3261144c892-aarch64-linux-gnu-debug.tar.gz
b3c1383fb394997378997bdd2933965cf4ecc694143b4703108ff6ecb946696c  guix-build-b3261144c892/output/aarch64-linux-gnu/bitcoin-b3261144c892-aarch64-linux-gnu.tar.gz
f43fedf3af666d35e83b84e63cfe19f315f74f01296982f47d8c159385c3b03c  guix-build-b3261144c892/output/arm-linux-gnueabihf/SHA256SUMS.part
73b89b0487e8eee474a6c9c96ae0e7ad635cccc332fc062eb5d4ff5555356c3e  guix-build-b3261144c892/output/arm-linux-gnueabihf/bitcoin-b3261144c892-arm-linux-gnueabihf-debug.tar.gz
b4518dd9396f316de8d7de5181b8b5d1083e0afa9081625c37117472d2559380  guix-build-b3261144c892/output/arm-linux-gnueabihf/bitcoin-b3261144c892-arm-linux-gnueabihf.tar.gz
0213e754408e2a032cef61a946354656f5b5f755f85aeac1ce4b37f1d22528e6  guix-build-b3261144c892/output/arm64-apple-darwin/SHA256SUMS.part
11bc1be1f53dad337565f3c556dd69abc2d702a31e661359daad6ff89225c794  guix-build-b3261144c892/output/arm64-apple-darwin/bitcoin-b3261144c892-arm64-apple-darwin-unsigned.dmg
558d8e805420c7a348759df6f559ca349953646aa28840efafe5a3d245ea917f  guix-build-b3261144c892/output/arm64-apple-darwin/bitcoin-b3261144c892-arm64-apple-darwin-unsigned.tar.gz
e679ce3f1c80aff11a5eab8890efbd0d396a851875fbd6f93f32eef5cdf06813  guix-build-b3261144c892/output/arm64-apple-darwin/bitcoin-b3261144c892-arm64-apple-darwin.tar.gz
0cb346390dc6620593b1af5b6669ddc3c1a8d2219a51b1697747c5ab24069c27  guix-build-b3261144c892/output/dist-archive/bitcoin-b3261144c892.tar.gz
ac8bd2d58d9d0ebe2da1c8efa2d57bd97c3ef2b2590c758edbc4919808c528c5  guix-build-b3261144c892/output/powerpc64-linux-gnu/SHA256SUMS.part
cdf8252fa8aca6da61ff6926de5c7e2e6560ab046049c84c26ba44823f83236a  guix-build-b3261144c892/output/powerpc64-linux-gnu/bitcoin-b3261144c892-powerpc64-linux-gnu-debug.tar.gz
3b8b5f53d365b5bf962ecd7def9f06b6f13af0e5c9ef69c6d028f1ed772459be  guix-build-b3261144c892/output/powerpc64-linux-gnu/bitcoin-b3261144c892-powerpc64-linux-gnu.tar.gz
b44e688d233dcb46a7d6d0b1d97979335d3cc559d16190cc5cd647add79298d2  guix-build-b3261144c892/output/powerpc64le-linux-gnu/SHA256SUMS.part
ae5c19afefd523cdc171a3f9aa9f707870fd99749c01c01166086619dfd95ece  guix-build-b3261144c892/output/powerpc64le-linux-gnu/bitcoin-b3261144c892-powerpc64le-linux-gnu-debug.tar.gz
bb581b1444fa1686f8889248af13d1859f2915091cd640bc522185d5ad83e13d  guix-build-b3261144c892/output/powerpc64le-linux-gnu/bitcoin-b3261144c892-powerpc64le-linux-gnu.tar.gz
bdca0a3c19b5a9a5c72b2b43b07050678d960009d3fa80cf7e0689d508346974  guix-build-b3261144c892/output/riscv64-linux-gnu/SHA256SUMS.part
b0b9c91abe2ad0b5ab3b0bfd10c90133d8d75b50aef0a6a98ac2c2ae4219eaa8  guix-build-b3261144c892/output/riscv64-linux-gnu/bitcoin-b3261144c892-riscv64-linux-gnu-debug.tar.gz
fcce0ea00f1d9df136dd677cbc468183faa92bd4bfcd4a77cd1c70f1b894b5f0  guix-build-b3261144c892/output/riscv64-linux-gnu/bitcoin-b3261144c892-riscv64-linux-gnu.tar.gz
7be84969950bb9570522be5a37551c01698cd3fb65eca3988fc9bd6867460552  guix-build-b3261144c892/output/x86_64-apple-darwin/SHA256SUMS.part
25203f50aa6a344ad1c6c4a44a48082440bb0af9bf38f0d60506569f216d1672  guix-build-b3261144c892/output/x86_64-apple-darwin/bitcoin-b3261144c892-x86_64-apple-darwin-unsigned.dmg
16c5baaf6d00ed43b0611c86c2d4555d500b3896daa1daac6a567bc2611c39f6  guix-build-b3261144c892/output/x86_64-apple-darwin/bitcoin-b3261144c892-x86_64-apple-darwin-unsigned.tar.gz
86662f39c29b013b576e6555ecb6cbbc98eaa08532a541e22a7ed6b1baf87209  guix-build-b3261144c892/output/x86_64-apple-darwin/bitcoin-b3261144c892-x86_64-apple-darwin.tar.gz
fbbc0ad2376431fdc5b214fd63f24a6da907d87f6f11e0833def50c0d45772cd  guix-build-b3261144c892/output/x86_64-linux-gnu/SHA256SUMS.part
cba8d700f746a6063809570e45d6dc3d5e60ad5f1a28e0f41f8beed8b546a7b1  guix-build-b3261144c892/output/x86_64-linux-gnu/bitcoin-b3261144c892-x86_64-linux-gnu-debug.tar.gz
0a32985a1e26e13ce883a85e4a92cc68bf51ce096f2f6d74ea499a9fa662d7d0  guix-build-b3261144c892/output/x86_64-linux-gnu/bitcoin-b3261144c892-x86_64-linux-gnu.tar.gz
0bd4cc64cd6ad733cdef87cd74d5034e79dd250b72795cebf9c2c63500509457  guix-build-b3261144c892/output/x86_64-w64-mingw32/SHA256SUMS.part
6ed8f2e6c6cf1992d156672707cd2c254754051f88223dd052a9cd9078d84789  guix-build-b3261144c892/output/x86_64-w64-mingw32/bitcoin-b3261144c892-win64-debug.zip
1ea6d7660652e20b2b1529e406be1f606745d35f6a179b006335a19a19aa9a5b  guix-build-b3261144c892/output/x86_64-w64-mingw32/bitcoin-b3261144c892-win64-setup-unsigned.exe
41b0f8cbac614e8c555921de60b25a73a75e6bed025de98ca40d3db48c5db6b1  guix-build-b3261144c892/output/x86_64-w64-mingw32/bitcoin-b3261144c892-win64-unsigned.tar.gz
5c68d711782e76f9e4be93b5468c505f022b72ca299532b200e58fe1e51343b1  guix-build-b3261144c892/output/x86_64-w64-mingw32/bitcoin-b3261144c892-win64.zip
```

### CODE REVIEW

**Comment by hebasto** [comment]
@MarcoFalke 

After the last push, the CI `merge_base_script` works in a wrong [way](https://api.cirrus-ci.com/v1/task/6187219250053120/logs/merge_base.log):
 ```
bash -c "$PACKAGE_MANAGER_INSTALL git"
Hit:1 https://mirror.hetzner.com/ubuntu/packages lunar InRelease
Hit:2 https://mirror.hetzner.com/ubuntu/packages lunar-updates InRelease
Hit:3 https://mirror.hetzner.com/ubuntu/packages lunar-backports InRelease
Hit:4 https://mirror.hetzner.com/ubuntu/security lunar-security InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.39.2-1ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
if [ "$CIRRUS_PR" = "" ]; then exit 0; fi
git fetch --depth=1 $CIRRUS_REPO_CLONE_URL "pull/${CIRRUS_PR}/merge"
From https://github.com/bitcoin-core/gui-qml
 * branch            refs/pull/359/merge -> FETCH_HEAD
git checkout FETCH_HEAD
Previous HEAD position was 592da16 Adjust code according to changes in the main repository
HEAD is now at 6f6e8b4 Merge b1f441ff3c280b4a59ccd2c15658628877830068 into 67895f77f2da6471c5c3b67988fde7f932f77782
M	ci/test/00_setup_env_native_asan.sh
```

The `HEAD` must be at `Merge 592da1615079d98afd81c074f0447122b718b125 into 67895f77f2da6471c5c3b67988fde7f932f77782`, no?

**Comment by hebasto** [comment]
> @MarcoFalke
> 
> After the last push, the CI `merge_base_script` works in a wrong [way](https://api.cirrus-ci.com/v1/task/6187219250053120/logs/merge_base.log):
> 
> ```
> bash -c "$PACKAGE_MANAGER_INSTALL git"
> Hit:1 https://mirror.hetzner.com/ubuntu/packages lunar InRelease
> Hit:2 https://mirror.hetzner.com/ubuntu/packages lunar-updates InRelease
> Hit:3 https://mirror.hetzner.com/ubuntu/packages lunar-backports InRelease
> Hit:4 https://mirror.hetzner.com/ubuntu/security lunar-security InRelease
> Reading package lists...
> Reading package lists...
> Building dependency tree...
> Reading state information...
> git is already the newest version (1:2.39.2-1ubuntu1.1).
> 0 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
> if [ "$CIRRUS_PR" = "" ]; then exit 0; fi
> git fetch --depth=1 $CIRRUS_REPO_CLONE_URL "pull/${CIRRUS_PR}/merge"
> From https://github.com/bitcoin-core/gui-qml
> * branch            refs/pull/359/merge -> FETCH_HEAD
> git checkout FETCH_HEAD
> Previous HEAD position was 592da16 Adjust code according to changes in the main repository
> HEAD is now at 6f6e8b4 Merge b1f441ff3c280b4a59ccd2c15658628877830068 into 67895f77f2da6471c5c3b67988fde7f932f77782
> M	ci/test/00_setup_env_native_asan.sh
> ```
> 
> The `HEAD` must be at `Merge 592da1615079d98afd81c074f0447122b718b125 into 67895f77f2da6471c5c3b67988fde7f932f77782`, no?

UPD. Or is it just an intermittent GitHub issue?

**Comment by hebasto** [comment]
> UPD. Or is it just an intermittent GitHub issue?

Looks like that. Re-run fixes it.

**Comment by hebasto** [comment]
Going to merge this PR to unlock migration from non-free Cirrus CI to free GitHub Actions.

Hoping someone will make post-merge review soon.

**Comment by promag** [comment]
utACK 14ddf6169358526ee5f349da2a7102dcd5dcd232.

ACK merge commit b7cdd31be

Light code review:
- b3261144c ci: Disable the ARM task temporarily
- 2719ce1ed Fix `modernize-use-default-member-init` clang-tidy warnings
- 8b025633e Adjust code according to changes in the main repository
- 81643a5ff ci, qml: Add required Qt Quick dev packages
- dea9e513a build, qt: Enable OpenGL for Windows static builds
- 3d78b7a40 qml, build: Update PE_ALLOWED_LIBRARIES for Qt 5.15.2
- 16f77a59d net: Notify about connection number by type

**Pull request merged**
