### PR TITLE
Introduce `PeersIndicator` component - An alternative design

### PR DESCRIPTION
**Pull request by hebasto**
Sorry, couldn't resist :)

Screenshot from 2022-06-04 08-09-54

Additional design feature:
- blinking if no connection established

---

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/128)
[macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/128)
[Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/128)

### CODE REVIEW

**Comment by hebasto** [comment]
Add blinking when no connection established yet.

**Review by jarolrod — COMMENTED** [review]
I prefer #127, but maybe this just needs a designers touch :)

ping: @GBKS @mouxdesign

**Review by shaavan — COMMENTED** [review]
I would agree with @jarolrod here,

Though this design style is synonym with the network strength a device is getting; I don't feel it suits very well according to our overall design system, at least not in the form it currently is.
Nonetheless, it is an interesting design choice, and I would love to hear @GBKS take on this.

**Comment by mouxdesign** [comment]
@jarolrod I am not able to see  the design on #127. However playing around with a network connection image that is very familiar to users might also be an idea. Most of the designs Christoph created are very round and circular, so am trying to keep with the design style here with this idea.
Group 6

**Comment by GBKS** [comment]
I think it could this style could work as well. Best to judge it in context of the full design, so I mocked it up here real quick (so much for getting my mind off of bitcoin over the vacation). 

Block clock bar peers 220607

On a general note, 5 bars (or dots) feels easier to parse than 10 bars (or dots) both visually (have to look more closely to identify the amount of white bars when there are 10) and logically (what is the difference to me as a user between 6 and 7 bars?).

**Comment by mouxdesign** [comment]
Very much like the indicator idea provided by @GBKS as it fits in very well with the current design elements. Indeed 5 bars to show load time would perhaps indeed show better visually as well as being more accessible with users with visual limitations. Might be interesting to see how Christophs design looks with the bitcoin logo in orange and the loading bars in orange as well. Just an idea! 

For the wording itself..I'm just wondering if words like "your connection" or "network connection" may be an idea as well.

**Comment by jarolrod** [comment]
This was closed because design suggestions are not to be made in this repo. To suggest a change to the design, an issue should be opened up here: https://github.com/BitcoinDesign/Bitcoin-Core-App/issues

Discussion on this will be moved to: https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/21

**Pull request closed without merging**
