### PR TITLE
Onboarding views navigation bar cleanup

### PR DESCRIPTION
**Pull request by jarolrod**
This reduces a bunch of duplicated code by properly abstracting the navigation bar of the onboarding view pages into components; the `OnboardingNav` and `NavButton` control.

These are extensible out of the box and will work for new types of elements that may be needed in the navigation bar in the future; extensibility is free for the future.

This and bitcoin-core/gui-qml#146 greatly simplify and correct the onboarding views.

This is also another way to fix the issue outlined in bitcoin-core/gui-qml#145 as we do away with the misuse of loaders.

Note to reviewers: please check the formatting of the UI with this change.

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/147)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/147)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/147)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/147)

### CODE REVIEW

**Comment by jarolrod** [comment]
updated from 66a9563 to 7243ed3 

changes: rebased over changes on master

**Comment by hebasto** [comment]
Still needs rebase :)

Suggesting to use `bitcoin-core/gui-qml#145` instead of just `#145` in the PR description as it goes in a merge commit message and dereferencing of `#145`depends on the repo when this commit resides.

**Comment by jarolrod** [comment]
Updated from 7243ed3 to ff1b0f8 

changes: rebased over changes on master

**Review by hebasto — APPROVED** [review]
ACK ff1b0f8b5893f001ac2cc6d64903c5b0aa792373, tested on Ubuntu 22.04.

**Pull request merged**
