### PR TITLE
Fix Onboarding width and padding to work on mobile

### PR DESCRIPTION
**Pull request by johnny9**
[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/178)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/178)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/178)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/178)

### CODE REVIEW

**Comment by johnny9** [comment]
MOBILE
BEFORE:
Screenshot_20221004-111455
Screenshot_20221004-111459
Screenshot_20221004-111503
Screenshot_20221004-111507
Screenshot_20221004-111509
Screenshot_20221004-111513
Screenshot_20221004-111515

AFTER:

Screenshot_20221004-092323
Screenshot_20221004-092328
Screenshot_20221004-092331
Screenshot_20221004-092402
Screenshot_20221004-092407
Screenshot_20221004-092411
Screenshot_20221004-092414

**Comment by johnny9** [comment]
Update from[ db77046 ](https://github.com/bitcoin-core/gui-qml/commit/db77046a274e9b4494b708d024d994d050f3bb9a)to[ 1a67cae](https://github.com/bitcoin-core/gui-qml/commit/1a67caebbf41d47d17ee781bcbafe4e3122d463a):
  - Fix whitespace error caught during CI lint

**Comment by johnny9** [comment]
> Just needs some further refinement and input from designers, I've included comparisons between master and the pr branch below on both mobile and desktop. As you can see, the current state of the changes does impact the layout on desktop as well, at least for our option buttons.

Good catch.  I'll go ahead and fix the constraints on the width of the options.

**Comment by johnny9** [comment]
Update from[ 6b7c5d0 ](https://github.com/bitcoin-core/gui-qml/commit/6b7c5d0647cfb34a5303aa70c3a15022deb9537f)to[ 92cec74 ](https://github.com/bitcoin-core/gui-qml/commit/92cec74dd6271c9b0724d33841891e1cef125772):
  - Fix width constraints on onboarding OptionButtons

**Comment by johnny9** [comment]
Here is what Desktop looks like after the latest update to the branch with "Layout.maximumWidth: 450" set for the onboarding OptionButtons.

| locations | options |
| -- | -- |

**Comment by johnny9** [comment]
Update from[ 92cec74 ](https://github.com/bitcoin-core/gui-qml/commit/92cec74dd6271c9b0724d33841891e1cef125772)to[ 068efa3 ](https://github.com/bitcoin-core/gui-qml/commit/068efa3977f391600f2cf17c253e2b5db3939212):
  - Use Math.min to constrain widths instead of an if statement
  - Remove extra line breaks in the Header above StorageOptions

**Comment by johnny9** [comment]
Here is what the Storage Options onboarding page looks like now without the extra line breaks in the description.  It should match the figma now.
fixbreaks

**Review by jarolrod — APPROVED** [review]
ACK 068efa3

Only issue is the line breaks on mobile, but that is a non-blocker for me here. This can be addressed in a follow-up. Tested on mobile and on desktop and provided screenshots below.

# Mobile
## Master
|   |   |   |   |   |   |   |
| - | - | - | - | - | - | - |
| Screenshot_20221017-184451 | Screenshot_20221017-184501 | Screenshot_20221017-184506 | Screenshot_20221017-184510 | Screenshot_20221017-184515 | Screenshot_20221017-184519 | Screenshot_20221017-184525 |

# PR
|   |   |   |   |   |   |   |
| - | - | - | - | - | - | - |
| Screenshot_20221017-183903 | Screenshot_20221017-183912 | Screenshot_20221017-183920 | Screenshot_20221017-183929 | Screenshot_20221017-183938 | Screenshot_20221017-183945 | Screenshot_20221017-183957 |








# Desktop
## Master 
|   |   |   |   |   |   |   |
| - | - | - | - | - | - | - |
| Screen Shot 2022-10-17 at 6 34 51 PM | Screen Shot 2022-10-17 at 6 35 35 PM | Screen Shot 2022-10-17 at 6 35 44 PM | Screen Shot 2022-10-17 at 6 35 53 PM | Screen Shot 2022-10-17 at 6 36 05 PM | Screen Shot 2022-10-17 at 6 36 14 PM | Screen Shot 2022-10-17 at 6 36 23 PM |

## PR
|   |   |   |   |   |   |   |
| - | - | - | - | - | - | - |
| Screen Shot 2022-10-17 at 6 35 03 PM | Screen Shot 2022-10-17 at 6 35 38 PM | Screen Shot 2022-10-17 at 6 35 47 PM | Screen Shot 2022-10-17 at 6 35 56 PM | Screen Shot 2022-10-17 at 6 36 08 PM | Screen Shot 2022-10-17 at 6 36 16 PM | Screen Shot 2022-10-17 at 6 36 29 PM |

**Pull request merged**
