### PR TITLE
Put BlockClock into an error state if node init fails

### PR DESCRIPTION
**Pull request by johnny9**
Initial step for adding error states to the NodeRunner

Link to github actions build artifacts.

[Build Artifacts]()

### CODE REVIEW

**Comment by johnny9** [comment]
Tested by starting up a pruned testnet node and then changing the prune settings

Screenshot from 2023-12-19 20-37-07

**Review by MarnixCroes — COMMENTED** [review]
tested: error is displayed when `reindex` is need, instead of infinite loading on master.

nit: would it be easy to remove HandCursor when there is the error?
as there is nothing to click on

**Comment by johnny9** [comment]
> nit: would it be easy to remove HandCursor wh

Yeah I noticed that as well. Should probably do that until the pop up view with the details is sorted out.

**Review by pablomartin4btc — COMMENTED** [review]
Concept ACK

Is it possible to add some small text/ description within the BlockClock? Like what kind of error... "init"? With a tooltip perhaps to show an extended description. As in the brainstorming issue #348 where you can see "No Wifi" within the "Paused" BlockClock state.

**Comment by GBKS** [comment]
We have some mock-ups for different error types in the [design docs](https://bitcoincore.app/block-clock/) (half-way down the page). Ideally, we can always know what the problem was and show a respective icon & message. Maybe not exactly, but the general error source is already helpful.

For errors that cannot be recognized, the mock-ups show "Error" and "Tap for details". If we want to go this route, we need to figure out what is shown when tapping. A full screen with a proper explanation, error log, tips to resolve, etc, like [here](https://bitcoin.design/guide/daily-spending-wallet/sending/#errors)?

**Comment by johnny9** [comment]
> Concept ACK
> 
> Is it possible to add some small text/ description within the BlockClock? Like what kind of error... "init"? With a tooltip perhaps to show an extended description. As in the brainstorming issue #348 where you can see "No Wifi" within the "Paused" BlockClock state.

This is ultimately the goal. In this PR, I've just implemented the portion that I'm certain about and would likely want to follow up afterwards with the description/details portion.

> We have some mock-ups for different error types in the [design docs](https://bitcoincore.app/block-clock/) (half-way down the page). Ideally, we can always know what the problem was and show a respective icon & message. Maybe not exactly, but the general error source is already helpful.
> 
> For errors that cannot be recognized, the mock-ups show "Error" and "Tap for details". If we want to go this route, we need to figure out what is shown when tapping. A full screen with a proper explanation, error log, tips to resolve, etc, like [here](https://bitcoin.design/guide/daily-spending-wallet/sending/#errors)?

What to show when tapping is what I'm uncertain about at the moment and was feeling like it might be a chance for me to pretend to be a designer a bit and play with figma. The mobile design looked good and just need to get a basic design for the Desktop.

**Review by pablomartin4btc — COMMENTED** [review]
tACK 03a8725c2e24165344c2c2ca0451a65239e5d54f

I've 2 issues running `bitcoin-qt` with this change:

<details>
<summary>
1. As soon the app starts up I got these 2 errors regarding qml components
</summary>

```
QVariant::load: unknown user type with name BitcoinUnits::Unit.
Running initialization in thread
qrc:/qml/components/BlockClock.qml:33:5: Unable to assign [undefined] to QString
```

</details>

<details>
<summary>
2. After the above, since I got an instance on a pruned node with some corrupted index (due to some break during <code>loadtxoutset</code>) and <code>bitcoin.conf</code> still referencing <code>blockfilterindex=1</code> and <code>coinstatsindex=1</code>. So, when I remove those indexing settings I got what @MarnixCroes <a href="https://github.com/bitcoin-core/gui-qml/pull/383#pullrequestreview-1791500329">described above</a> -> "infinite loading on master". Should I not get the error icon also in this case? How I can validate this change? @johnny9 could you please add repro instructions on the description?
</summary>

```
Error: basic block filter index best block of the index goes beyond pruned data. Please disable the index or reindex (which will download the whole blockchain again)
Error: Failed to start indexes, shutting down.

```

</details>

<details>
<summary>Complete terminal error logs</summary>

```
~/workspace/bitcoin-core-gui-qml$ ./src/qt/bitcoin-qt 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QVariant::load: unknown user type with name BitcoinUnits::Unit.
Running initialization in thread
qrc:/qml/components/BlockClock.qml:33:5: Unable to assign [undefined] to QString
Error: basic block filter index best block of the index goes beyond pruned data. Please disable the index or reindex (which will download the whole blockchain again)
Error: Failed to start indexes, shutting down.

```
</details>

**Comment by johnny9** [comment]
Update from[ 03a8725 ](https://github.com/bitcoin-core/gui-qml/commit/03a8725c2e24165344c2c2ca0451a65239e5d54f)to 2b61d22
  - Removed invalid property from BlockClock.qml. this was leftover from previous work on this.

**Comment by johnny9** [comment]
> I've 2 issues running `bitcoin-qt` with this change:
> 1. As soon the app starts up I got these 2 errors regarding qml components
> 
> ```
> QVariant::load: unknown user type with name BitcoinUnits::Unit.
> Running initialization in thread
> qrc:/qml/components/BlockClock.qml:33:5: Unable to assign [undefined] to QString
> ```
I removed the invalid property in the latest update which resolved that error

> 2. After the above, since I got an instance on a pruned node with some corrupted index (due to some break during `loadtxoutset`) and `bitcoin.conf` still referencing `blockfilterindex=1` and `coinstatsindex=1`. So, when I remove those indexing settings I got what @MarnixCroes [described above](https://github.com/bitcoin-core/gui-qml/pull/383#pullrequestreview-1791500329) -> "infinite loading on master". Should I not get the error icon also in this case? How I can validate this change? @johnny9 could you please add repro instructions on the description?
> Complete terminal error logs
This won't catch all errors and there will need to be an effort to categorize all of these possible error states as well as render a description of what happened to the user.

This change triggers when `void NodeModel::initializeResult(bool success, interfaces::BlockAndHeaderTipInfo tip_info)` callback has `success = false` as a parameter. The specific case I use to test is to start up a signet node with `prune=1907` (the default you get with our onboarding flow). Then after it syncs a bit, I remove the `prune` option in my settings.json and restart the app.

**Review by pablomartin4btc — COMMENTED** [review]
tACK 2b61d228859af296a64f47977953f51cbedc42fc

I've managed to reproduce the errored BlockClock picture when there's another instance of Bitcoin Core running:

image

Also the [error reported in previous review](https://github.com/bitcoin-core/gui-qml/pull/383#pullrequestreview-1846795045) regarding the error on `BlockClock.qml` component doesn't show anymore:

```
./src/qt/bitcoin-qt -signet
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
Running initialization in thread
Error: Unable to bind to 0.0.0.0:38333 on this computer. Bitcoin Core is probably already running.
Error: Failed to listen on any port. Use -listen=0 if you want this
```

**Comment by GBKS** [comment]
Related, but probably not essential to this PR, here's an idea for handling errors. So on the left, we have this old mock-up for a tooltip that appears when hovering the peers dots, to give you slightly more info about connectivity. Clicking would take you to the peers page.

Now, we can take a similar approach to errors. Based on the type of error, a click can either show the tooltip or take you to the page relevant to this error (the page then needs to show appropriate information). 

What do you make of this pattern?

image

**Review by D33r-Gee — COMMENTED** [review]
tested on Ubuntu 22.04 and Android (Galaxy A13)

Was able to reproduce error on Ubuntu 22.04 by deleting the `index` directory located at `.bitcoin/signet/block`

For android used Android Studio IDE and deleted the `index` folder using the device explorer

Suggestion (echoing @GBKS): it would be nice if there was an error message in the GUI similar to what is displayed in terminal, i.e.:
 `: Error initializing block database.
Please restart with -reindex or -reindex-chainstate to recover.`

**Comment by GBKS** [comment]
> Please restart with -reindex or -reindex-chainstate to recover.

Is there a way to automatically restart with these options so the user can just click a button?

**Comment by MarnixCroes** [comment]
> > Please restart with -reindex or -reindex-chainstate to recover.
> 
> Is there a way to automatically restart with these options so the user can just click a button?

it's possible, best would be to do it as a follow up imo

**Review by MarnixCroes — APPROVED** [review]
tACK 2b61d228859af296a64f47977953f51cbedc42fc

**Pull request merged**
