### PR TITLE
Add looping animation to Estimating state

### PR DESCRIPTION
**Pull request by jarolrod**
Implements the following design: https://github.com/BitcoinDesign/Bitcoin-Core-App/issues/48

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/unsecure_win_gui.zip?branch=pull/325)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/unsecure_mac_gui.zip?branch=pull/325)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/unsecure_mac_arm64_gui.zip?branch=pull/325)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/unsecure_android_apk.zip?branch=pull/325)

### CODE REVIEW

**Comment by GBKS** [comment]
Looking good, I think it helps, although it feels just a tad too strong, especially when you also have the peer dots blinking. Could we try animating between Neutral 4 and Neutral 6, please?

It also feels like this animates with a very slow frame rate, like it's lagging a bit (on a very fast MacBook). Do you see the same?

**Comment by jarolrod** [comment]
Updated from [a41be94 ](https://github.com/bitcoin-core/gui-qml/commit/a41be946ee09c4e1748e2539357a6474b749972c)to [c95771e](https://github.com/bitcoin-core/gui-qml/commit/c95771e078026d953a7bd1c498298325aa90942d), [compare](https://github.com/bitcoin-core/gui-qml/compare/a41be946ee09c4e1748e2539357a6474b749972c..c95771e078026d953a7bd1c498298325aa90942d)

Changes: addressed [review](https://github.com/bitcoin-core/gui-qml/pull/325#issuecomment-1517421367) feedback

@GBKS I don't notice any animation issues

**Comment by jarolrod** [comment]
updated from [c95771e ](https://github.com/bitcoin-core/gui-qml/commit/c95771e078026d953a7bd1c498298325aa90942d)to [1271377](https://github.com/bitcoin-core/gui-qml/commit/1271377ccd80a4484845acabd7c61418fd2247ef)

changes: rebased over main

**Comment by GBKS** [comment]
ACK https://github.com/bitcoin-core/gui-qml/pull/325/commits/1271377ccd80a4484845acabd7c61418fd2247ef

**Pull request merged**
