### PR TITLE
Introduce reusable CaretRightButton, bind color to Setting stateColor

### PR DESCRIPTION
**Pull request by jarolrod**
This finishes setting up all current Settings to be able to respond to the Setting state.

| Filled | Hover | Active |
| ------ | ----- | ------ |
| Screen Shot 2023-02-01 at 2 12 02 AM | Screen Shot 2023-02-01 at 2 12 11 AM | Screen Shot 2023-02-01 at 2 12 19 AM |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/242)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/242)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/242)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/242)

### CODE REVIEW

**Comment by jarolrod** [comment]
updated from[ 37d2019 ](https://github.com/bitcoin-core/gui-qml/commit/37d20198a8aed393c6417f309b726c2012cc2dec)to [33b68b3](https://github.com/bitcoin-core/gui-qml/commit/33b68b34259aef6bfab47d9d0bbee6e52771c3b2), [compare](https://github.com/bitcoin-core/gui-qml/compare/37d20198a8aed393c6417f309b726c2012cc2dec..33b68b34259aef6bfab47d9d0bbee6e52771c3b2)

Changes: rebased over main

**Comment by hebasto** [comment]
> Based on #241

It has been just merged. Rebase?

**Comment by jarolrod** [comment]
Updated [from ](https://github.com/bitcoin-core/gui-qml/pull/242#event-8438941814)[33b68b3 ](https://github.com/bitcoin-core/gui-qml/commit/33b68b34259aef6bfab47d9d0bbee6e52771c3b2)to [624d985 ](https://github.com/bitcoin-core/gui-qml/commit/624d985542c0983e8e0e33baa1bf47b137373d82), [Compare](https://github.com/bitcoin-core/gui-qml/compare/33b68b34259aef6bfab47d9d0bbee6e52771c3b2..624d985542c0983e8e0e33baa1bf47b137373d82)

Changes: rebased over main

**Review by johnny9 — APPROVED** [review]
ACK 624d985542c0983e8e0e33baa1bf47b137373d82

**Pull request merged**
