### PR TITLE
Introduce `OptionsQmlModel` class to bind node settings with GUI

### PR DESCRIPTION
**Pull request by hebasto**
This PR adds only a basic implementation with a support for the `-prune` setting only.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @jarolrod

**Comment by johnny9** [comment]
I see 
```
2022-10-27T18:02:45Z GUI: qrc:/qml/components/StorageSettings.qml:24: TypeError: Cannot read property 'pruneSizeGB' of null
2022-10-27T18:02:45Z GUI: qrc:/qml/components/StorageSettings.qml:16: TypeError: Cannot read property 'prune' of null
```
in debug.log

**Comment by johnny9** [comment]
I believe you need to use qmlRegisterSingletonType and then import the registered module in order to access the object in the StorageSettings component. It seems only the root component has access to the object when using setContextProperty.

**Review by shaavan — COMMENTED** [review]
Concept ACK

The implementation looks standard. But as @johnny9 suggested, we can experiment using the `qmlRegisterSingletonType`.

@hebasto 
I know you are currently occupied with finishing the CMake project, so I would like to share the burden of the work with you.
I want to work forward on this branch if that's okay with you. Thank you.

**Comment by jarolrod** [comment]
@shaavan @johnny9 registering with the qml macro makes qml responsible for the lifecycle of the optionsmodel, we wouldn't want that. The way around this would be to subclass the qml engine, but there's no strong use-case for that right now.

**Comment by johnny9** [comment]
Is that something unique to using the macro?  Is there not an equivalent of qmlRegisterSingletonInstance using the macros to allow you to manage the lifecycle yourself?

**Comment by johnny9** [comment]
Ok I found what you were referring to here https://doc-snapshots.qt.io/qt5-5.15/qqmlengine.html#QML_SINGLETON.  Sounds like we should continue to use qmlRegisterSingletonType to override ownership of the object if we decide to use the macros.

**Comment by jarolrod** [comment]
@johnny9 seems that you are correct in suggesting we use `qmlRegisterSingletonInstance` for many reasons including the performance hit of context properties and the non-constant lookup time. The ownership of the object can stay with c++ and not with the qml engine by specifying the `QQmlEngine::CppOwnership` flag.

**Pull request closed without merging**
