### PR TITLE
Make External Link settings icon follow the design file specs

### PR DESCRIPTION
**Pull request by jarolrod**
This replaces the current export icon we have (export-filled) for the export-outline icon, as that is what the design file now specifies. The new icon has been passed through the `optimize-png.py` script, which output the following:

```
optimizing export.png... done
summary:
+++++++++++++++++
export.png
  size diff from: 1371 to: 785
  old sha256: c93640af06071bcee055727bcfd01f8576d657260a385035dac8f2f1568cf571
  new sha256: c0605b933dfaae15b26254d08d11d2e9e9e4b20d5a9748386cd9a9f680502266

completed. Checksum stable: False. Total reduction: 586 bytes
```

Additionally, this adjusts the spacing between the external link text and the icon in order to better match the design file

### master
| light | dark |
| ----- | ---- |
| Screen Shot 2023-01-31 at 7 08 22 PM | Screen Shot 2023-01-31 at 7 08 28 PM |

### pr

| light | dark |
| ----- | ---- |
| Screen Shot 2023-02-09 at 1 42 16 PM | Screen Shot 2023-02-09 at 1 42 22 PM |

### layout

| external icon | right caret |
| ------------- | ----------- |
| Screen Shot 2023-02-09 at 1 41 33 PM |  Screen Shot 2023-02-09 at 1 41 44 PM |

[Windows](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/win64/insecure_win_gui.zip?branch=pull/239)
[Intel macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos/insecure_mac_gui.zip?branch=pull/239)
[Apple Silicon macOS](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/macos_arm64/insecure_mac_arm64_gui.zip?branch=pull/239)
[ARM64 Android](https://api.cirrus-ci.com/v1/artifact/github/bitcoin-core/gui-qml/android/insecure_android_apk.zip?branch=pull/239)

### CODE REVIEW

**Review by johnny9 — COMMENTED** [review]
The new icon expanded the spacing on the layout. I think adjusting spacing from 20 to 15 in AboutOptions and Settings.qml fixes it but unsure of the side effects of that with the other views

**Comment by jarolrod** [comment]
@johnny9 @GBKS

Is that really an issue? There's no clear spec for how tall a setting should be, for example settings with descriptions are taller

**Comment by GBKS** [comment]
List items can indeed scale vertically to fit whatever content needs to be shown. I tried to shoot for a default height of 50px for items that have just one line of text and icon left/right. 44 is the minimum hit area recommended for mobile, and 50 is just a little more convenient. Too much space, and you end up with pretty tall screens with somewhat low information density.

**Comment by hebasto** [comment]
Rebase?

**Comment by jarolrod** [comment]
Updated from [3874d63 ](https://github.com/bitcoin-core/gui-qml/commit/3874d63f93cf83ea90c6e93c07b6f11c07d9f822)to [515e2fa](https://github.com/bitcoin-core/gui-qml/commit/515e2fae2d48470dcd5318b6a0c985eab5eaa912), [compare](https://github.com/bitcoin-core/gui-qml/compare/3874d63f93cf83ea90c6e93c07b6f11c07d9f822..515e2fae2d48470dcd5318b6a0c985eab5eaa912)

Changes:
- rebased over main to resolve conflicts
- Fixed layout issue by getting us as close to the design file as I can without spending too many more hours over 2 pixels :D

**Review by johnny9 — APPROVED** [review]
ACK 515e2fae2d48470dcd5318b6a0c985eab5eaa912

**Pull request merged**
