### PR TITLE
Add basic QML support to Qt resource system

### PR DESCRIPTION
**Pull request by hebasto**
Added basic support for QML to Qt resource system.

Suggested the following file directory layout:
- `src/qml/`
- `src/qml/*.{h|cpp}`
- `src/qml/pages/*.qml`
- `src/qml/<other resource directories>`

### CODE REVIEW

**Review by jarolrod — COMMENTED** [review]
Concept ACK

Tested on macOS 11.3, can produce the stub window 🎉 (very aesthetic). Will review more in depth after you rebase on top of the changes to #2 and merge #4.

Screen Shot 2021-07-05 at 8 14 29 PM

**Comment by hebasto** [comment]
> Will review more in depth after you rebase on top of the changes to #2 and merge #4.

Rebased and ready :)

**Review by promag — COMMENTED** [review]
Approack ACK. Initially I though having this under src/qt but having separate seems preferable to avoid conflicts. Will test.

**Review by promag — COMMENTED** [review]
ACK e2104f8909. Comparing to https://github.com/bitcoin/bitcoin/pull/16883 I prefer this approach especially because we can change the startup without affecting the existing bitcoin-qt.

**Pull request merged**
